// Proof harness for the browser-side plan matcher + the two inline guards (RULE THREE — pick, don't type).
// Re-implements matchesFacet / countMatches / countOverlap from
// src/app/(platform)/commcalc/_lib/planMatch.tsx VERBATIM (no DOM/React), then:
//   1. replays the CASE GRID generated by backend/scratchpad/plan_options_proof.py, whose `expect` values
//      come from commission_engine._rule_matches itself — so the warning shown in the editor cannot
//      disagree with the engine that pays;
//   2. drives the real double-pay scenario (two overlapping product_desc CONTAINS patterns) and the
//      dead-rule case;
//   3. greps the .tsx for the exact bodies (source-parity, same convention as prove_entity_picker.mjs).
// Run:  node frontend/scratchpad/prove_plan_match.mjs
import { readFileSync } from 'node:fs'

let PASS = 0, FAIL = 0
const ok = (name, cond, extra = '') => {
  if (cond) { PASS++; console.log(`  ok  ${name}`) }
  else { FAIL++; console.log(`FAIL  ${name}   ${extra}`) }
}

// ── verbatim from planMatch.tsx ──────────────────────────────────────────────────────────────────
const norm = (v) => (v ?? '').toString().trim().toLowerCase()

function matchesFacet(get, rule, ctResolved) {
  const field = norm(rule.match_field || 'any')
  if (field === 'any') return true
  const op = norm(rule.match_op || 'equals')
  const want = norm(rule.match_value || '')
  const candidates = [norm(get(field))]
  if (field === 'contract_type' && ctResolved !== undefined) {
    const alt = norm(ctResolved)
    if (alt && alt !== candidates[0]) candidates.push(alt)
  }
  for (const have of candidates) {
    if (op === 'contains') { if (want !== '' && have.includes(want)) return true }
    else if (op === 'in') {
      const opts = want.split(',').map(s => s.trim()).filter(Boolean)
      if (opts.includes(have)) return true
    } else if (have === want) return true
  }
  return false
}

function analysable(opts, rule) {
  const f = norm(rule.match_field || 'any')
  if (!opts?.facets) return false
  return f === 'any' || opts.facets.columns.includes(f)
}

function rowReader(fx, row) {
  const get = (col) => {
    const i = fx.columns.indexOf(col)
    return i < 0 ? '' : (fx.dict[col]?.[row[i]] ?? '')
  }
  const ct = fx.ct_resolved ? (fx.ct_resolved[row[fx.columns.length]] ?? '') : undefined
  return { get, ct, lines: row[row.length - 1] || 0 }
}

function countMatches(opts, rule) {
  const fx = opts?.facets
  if (!fx || !analysable(opts, rule)) return null
  let lines = 0, rows = 0
  for (const row of fx.rows) {
    const r = rowReader(fx, row)
    if (matchesFacet(r.get, rule, r.ct)) { lines += r.lines; rows++ }
  }
  return { lines, rows }
}

function countOverlap(opts, a, b) {
  const fx = opts?.facets
  if (!fx || !analysable(opts, a) || !analysable(opts, b)) return null
  let lines = 0
  for (const row of fx.rows) {
    const r = rowReader(fx, row)
    if (matchesFacet(r.get, a, r.ct) && matchesFacet(r.get, b, r.ct)) lines += r.lines
  }
  return lines
}

// ── 1. replay the engine-generated case grid ─────────────────────────────────────────────────────
console.log('── 1. parity with commission_engine._rule_matches (engine-generated grid) ──')
let grid
try {
  grid = JSON.parse(readFileSync(new URL('../../backend/scratchpad/plan_match_cases.json', import.meta.url), 'utf8'))
} catch (e) {
  console.log('FAIL  plan_match_cases.json missing — run backend/scratchpad/plan_options_proof.py first')
  process.exit(1)
}
let checked = 0, wrong = 0
for (const c of grid.cases) {
  if (c.expect === null) continue                       // synthetic field: not analysable either side
  const get = (col) => c.row[col] ?? ''
  const got = matchesFacet(get, c.rule)
  checked++
  if (got !== c.expect) { wrong++; console.log(`   mismatch: ${JSON.stringify(c.rule)} on ${JSON.stringify(c.row)} → ${got} != ${c.expect}`) }
}
ok(`${checked} engine cases replay identically in the browser mirror`, wrong === 0 && checked > 30, `${wrong} wrong`)
ok('synthetic-field cases are excluded on BOTH sides (never a wrong warning)',
  grid.cases.some(c => c.expect === null && c.rule.match_field === 'accessory'))
ok('facet columns agree with the backend',
  JSON.stringify(grid.columns) === JSON.stringify(['department', 'category', 'contract_type', 'tender_type', 'trans_type', 'product_desc', 'sku']),
  JSON.stringify(grid.columns))

// ── 2. the real owner scenario ───────────────────────────────────────────────────────────────────
console.log('── 2. the $10 double-pay scenario + the dead rule ──')
const COLS = ['department', 'category', 'contract_type', 'tender_type', 'trans_type', 'product_desc', 'sku']
const dict = {
  department: ['Internet', 'Accessories'],
  category: ['Home Internet', 'Cases'],
  contract_type: ['New Activation', ''],
  tender_type: ['', 'Acima'],
  trans_type: ['Sale'],
  product_desc: ['Home Internet Gateway', 'VHI Home Internet Router', 'Otterbox Case'],
  sku: [''],
}
const opts = {
  facets: {
    columns: COLS, dict, ct_resolved: null,
    rows: [
      [0, 0, 0, 0, 0, 0, 0, 5],    // 5 × Home Internet Gateway
      [0, 0, 0, 0, 0, 1, 0, 3],    // 3 × VHI Home Internet Router
      [1, 1, 1, 1, 0, 2, 0, 7],    // 7 × Otterbox Case
    ],
    truncated: false, lines_covered: 15, lines_total: 15,
  },
  window: { months: 3 },
}
const rHome = { match_field: 'product_desc', match_op: 'contains', match_value: 'home internet' }
const rVhi = { match_field: 'product_desc', match_op: 'contains', match_value: 'vhi' }
const rCase = { match_field: 'category', match_op: 'equals', match_value: 'Cases' }
const rTypo = { match_field: 'category', match_op: 'equals', match_value: 'Home Internett' }
const rNonQual = { match_field: 'product_desc', match_op: 'contains', match_value: 'router', qualifies: false }

ok("'home internet' matches 8 lines (both products)", countMatches(opts, rHome).lines === 8, JSON.stringify(countMatches(opts, rHome)))
ok("'vhi' matches 3 lines", countMatches(opts, rVhi).lines === 3)
ok('the OVERLAP is exactly the 3 VHI lines (the double-pay the owner hit)', countOverlap(opts, rHome, rVhi) === 3)
ok('a disjoint rule reports NO overlap', countOverlap(opts, rHome, rCase) === 0)
ok('a typo matches nothing (the dead-rule guard fires)', countMatches(opts, rTypo).lines === 0)
ok('counts are LINES, not facet rows', countMatches(opts, rHome).rows === 2)
ok("a blanket 'any' rule matches every line", countMatches(opts, { match_field: 'any' }).lines === 15)
ok('a synthetic field is not analysable (no count, no false warning)',
  countMatches(opts, { match_field: 'activation_bucket', match_op: 'equals', match_value: 'premium' }) === null)
ok('overlap with a NON-qualifying rule is still computed (the UI filters it, the math does not lie)',
  countOverlap(opts, rHome, rNonQual) === 3)
ok('an empty CONTAINS pattern matches nothing (mirrors the engine)',
  countMatches(opts, { match_field: 'product_desc', match_op: 'contains', match_value: '' }).lines === 0)
ok("op 'in' matches any of the comma list",
  countMatches(opts, { match_field: 'category', match_op: 'in', match_value: 'cases, phones' }).lines === 7)
ok('an equals on a BLANK value matches the blank lines (a real trap, shown honestly)',
  countMatches(opts, { match_field: 'contract_type', match_op: 'equals', match_value: '' }).lines === 7)

// mapped contract-type resolution (mig 232): the resolved bucket is a second candidate
const mapped = JSON.parse(JSON.stringify(opts))
mapped.facets.ct_resolved = ['premium', '']
mapped.facets.rows = [[0, 0, 0, 0, 0, 0, 0, 0, 5], [0, 0, 0, 0, 0, 1, 0, 0, 3], [1, 1, 1, 1, 0, 2, 0, 1, 7]]
ok("mapped mode: contract_type equals 'premium' matches the resolved lines",
  countMatches(mapped, { match_field: 'contract_type', match_op: 'equals', match_value: 'premium' }).lines === 8)
ok('raw mode: the same rule matches nothing',
  countMatches(opts, { match_field: 'contract_type', match_op: 'equals', match_value: 'premium' }).lines === 0)

// ── 3. source parity with the .tsx ───────────────────────────────────────────────────────────────
console.log('── 3. source parity with planMatch.tsx ──')
const src = readFileSync(new URL('../src/app/(platform)/commcalc/_lib/planMatch.tsx', import.meta.url), 'utf8')
const bodies = [
  "const norm = (v: unknown) => (v ?? '').toString().trim().toLowerCase()",
  "if (field === 'any') return true",
  "if (op === 'contains') { if (want !== '' && have.includes(want)) return true }",
  "const opts = want.split(',').map(s => s.trim()).filter(Boolean)",
  "if (opts.includes(have)) return true",
  '} else if (have === want) return true',
  "if (field === 'contract_type' && ctResolved !== undefined) {",
  'const ct = fx.ct_resolved ? (fx.ct_resolved[row[fx.columns.length]] ?? \'\') : undefined',
  'if (matchesFacet(r.get, a, r.ct) && matchesFacet(r.get, b, r.ct)) lines += r.lines',
]
for (const b of bodies) ok(`tsx contains: ${b.slice(0, 58)}…`, src.includes(b))
ok('the picker only allows free entry for contains / free-text / truncated / empty lists',
  src.includes("const allowCreate = !isAny && (o === 'contains' || !!info?.free_text || !!info?.truncated || !info")
  && src.includes('|| (info.values?.length ?? 0) === 0)'))
ok('zero-wipe: a saved value is always re-offered as an option',
  src.includes('// ZERO-WIPE: a value already saved on the plan is ALWAYS offered'))
ok("op 'in' uses a MULTI picker that stores the comma list the engine parses",
  src.includes('onChange={ids => onChange(ids.join(\',\'))}'))

console.log()
console.log(`${PASS} passed, ${FAIL} failed`)
process.exit(FAIL ? 1 : 0)
