-- MIGRATION 724: POS MODULE — CORE CATALOG (Phase 0 of the POS-inside-MetricsPro port)
-- Run this in the Supabase SQL editor. Follows the 004_module_template pattern.
-- Creates the pos.* schema with the product catalog (departments, categories, products).
-- Employees/stores/roles/tenancy are NOT duplicated here: POS rows reference
-- storeops.employees.employee_id (TEXT business key) and storeops.stores.store_code
-- by convention, exactly like every other module.
-- Later phases add: customers, inventory, sales/checkout, activations, purchase orders.

CREATE SCHEMA IF NOT EXISTS pos;

-- Departments (top level of the retail catalog, e.g. Accessories / Phones / Services).
CREATE TABLE IF NOT EXISTS pos.departments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  short_name TEXT NOT NULL,
  full_name TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, short_name)
);

-- Categories (optionally nested under a department).
CREATE TABLE IF NOT EXISTS pos.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  name TEXT NOT NULL,
  department_id UUID REFERENCES pos.departments(id),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, name)
);

-- Products & services. product_code is the human-facing number shown at the register;
-- the sequence is global but uniqueness is enforced per org.
CREATE TABLE IF NOT EXISTS pos.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  product_code BIGINT GENERATED BY DEFAULT AS IDENTITY,
  upc TEXT,
  short_name TEXT NOT NULL,
  full_name TEXT,
  department_id UUID REFERENCES pos.departments(id),
  category_id UUID REFERENCES pos.categories(id),
  system_category TEXT CHECK (system_category IN ('Accessory','Cell Phone','Regular','Service')),
  inventory_type TEXT NOT NULL DEFAULT 'standard' CHECK (inventory_type IN ('standard','serial')),
  manufacturer TEXT,                -- free text until pos vendors land (Phase 2)
  cost NUMERIC(12,2) DEFAULT 0,
  retail_price NUMERIC(12,2) DEFAULT 0,
  msrp NUMERIC(12,2),               -- needed later for rebate/bundled tax methods
  is_taxable BOOLEAN DEFAULT true,
  calculate_as_profit BOOLEAN DEFAULT true,
  body_style TEXT,
  is_active BOOLEAN DEFAULT true,
  end_of_life BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, product_code)
);
CREATE INDEX IF NOT EXISTS pos_products_org_active ON pos.products(org_id, is_active);
CREATE INDEX IF NOT EXISTS pos_products_upc ON pos.products(org_id, upc);

-- ── Security: mirror 722_core_security_anon_lockdown for the NEW schema ────────────────────────────
-- Backend-only access (service_role bypasses RLS); no client-side data path, ever.
DO $$
DECLARE t RECORD;
BEGIN
  EXECUTE 'GRANT USAGE ON SCHEMA pos TO service_role';
  EXECUTE 'REVOKE ALL ON SCHEMA pos FROM anon, authenticated';
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'pos' LOOP
    EXECUTE format('ALTER TABLE pos.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  EXECUTE 'REVOKE ALL ON ALL TABLES    IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'GRANT ALL ON ALL TABLES    IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA pos TO service_role';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos REVOKE ALL ON TABLES    FROM anon, authenticated';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos REVOKE ALL ON SEQUENCES FROM anon, authenticated';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos REVOKE ALL ON FUNCTIONS FROM anon, authenticated';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos GRANT ALL ON TABLES    TO service_role';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos GRANT ALL ON SEQUENCES TO service_role';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA pos GRANT ALL ON FUNCTIONS TO service_role';
END $$;
