-- MIGRATION 725: POS MODULE — PHASE 1: CUSTOMERS, INVENTORY, SALES/CHECKOUT, REGISTER, CONFIG
-- Run this in the Supabase SQL editor (after 724). Idempotent.
--
-- Ports the transactional core of the standalone pos-system app into the pos.* schema:
--   customers (+ encrypted PII), customer notes, serial + standard inventory,
--   sales/sale_items/sale_payments with an ATOMIC pos.checkout() (the old app did three
--   separate client inserts — a partial sale was a reachable state), void_sale,
--   register (cash drawer) sessions with server-computed variance, the pos_settings
--   config kv (org default → per-store override), tax codes, and receipt templates.
--
-- Identity conventions (same as every module, see mig 724 header):
--   * org_id UUID on every row.
--   * stores referenced by storeops.stores.store_code (TEXT), column name store_code.
--   * employees referenced by storeops.employees.employee_id (TEXT business key —
--     NEVER the numeric PK, see mig 415).
--   * No auth.uid() anywhere: the backend calls with the service role and passes the
--     acting employee explicitly; RBAC lives in the FastAPI layer.
--
-- Differences from the standalone app, on purpose:
--   * sales.receipt JSONB — full receipt snapshot at checkout (the old app kept
--     tendered/change only in React state; they were unrecoverable after the modal).
--   * org_settings.tax_applied_on became the pos_settings key 'tax_applied_on'.
--   * Columns the old code never touched (dnb_number, price_profile, precash_account_no,
--     home_location_id, assigned_sales_rep_id) are dropped; Phase 3 data migration can
--     re-add if real data shows up in them.

CREATE SCHEMA IF NOT EXISTS pos;

-- ── Customers ──────────────────────────────────────────────────────────────────────────────────────
-- PII: ssn/driver-license ciphertext only (pgp_sym_encrypt, key in Vault). The database never
-- holds plaintext; access only via the pos.customer_pii_* functions below.
CREATE TABLE IF NOT EXISTS pos.customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  cust_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_type TEXT DEFAULT 'Personal' CHECK (account_type IN ('Personal','Business')),
  company_name TEXT,
  first_name TEXT,
  last_name TEXT,
  middle_initial TEXT,
  dob DATE,
  driver_license_state TEXT,          -- 2-letter code; deliberately plaintext (filterable, not sensitive alone)
  primary_account_no TEXT,
  password TEXT,                      -- carrier "account password/PIN" the customer sets, not a login credential
  email TEXT,
  phone_primary TEXT,
  phone_secondary TEXT,
  address_1 TEXT,
  address_2 TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  referral_source TEXT,
  credit_limit NUMERIC(12,2) DEFAULT 0,
  accept_checks BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  ssn_enc BYTEA,                      -- pgp_sym_encrypt(ssn, vault:pos_pii_encryption_key)
  driver_license_enc BYTEA,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, cust_number)
);
CREATE INDEX IF NOT EXISTS pos_customers_org_active ON pos.customers(org_id, is_active);
CREATE INDEX IF NOT EXISTS pos_customers_phone ON pos.customers(org_id, phone_primary);
CREATE INDEX IF NOT EXISTS pos_customers_name ON pos.customers(org_id, last_name, first_name);

COMMENT ON COLUMN pos.customers.ssn_enc IS
  'pgp_sym_encrypt(ssn, vault:pos_pii_encryption_key). Read/write only via pos.customer_pii_*.';
COMMENT ON COLUMN pos.customers.driver_license_enc IS
  'pgp_sym_encrypt(driver_license_num, vault:pos_pii_encryption_key). Read/write only via pos.customer_pii_*.';

CREATE TABLE IF NOT EXISTS pos.customer_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  customer_id UUID NOT NULL REFERENCES pos.customers(id) ON DELETE CASCADE,
  employee_id TEXT,                   -- storeops.employees.employee_id of the author
  note TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'normal' CHECK (severity IN ('normal','important','urgent')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_customer_notes_cust ON pos.customer_notes(customer_id, created_at DESC);

-- ── Inventory ──────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.inventory_serial (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  product_id UUID NOT NULL REFERENCES pos.products(id),
  store_code TEXT,                    -- storeops.stores.store_code; null = unassigned
  serial_number TEXT NOT NULL,
  imei TEXT,
  sim_card TEXT,
  color TEXT,
  storage TEXT,
  condition TEXT DEFAULT 'new' CHECK (condition IN ('new','refurbished','used','damaged')),
  status TEXT DEFAULT 'in_stock'
         CHECK (status IN ('in_stock','in_transit','sold','returned','transferred','rma','lost','stolen')),
  cost NUMERIC(12,2),
  date_received DATE,
  po_number TEXT,
  sold_at TIMESTAMPTZ,                -- written by the checkout trigger only
  sold_in_sale_id UUID,               -- FK added below (sales table defined later in this file)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_inv_serial_org_status ON pos.inventory_serial(org_id, status);
CREATE INDEX IF NOT EXISTS pos_inv_serial_serial ON pos.inventory_serial(org_id, serial_number);
CREATE INDEX IF NOT EXISTS pos_inv_serial_imei ON pos.inventory_serial(org_id, imei);

CREATE TABLE IF NOT EXISTS pos.inventory_standard (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  product_id UUID NOT NULL REFERENCES pos.products(id),
  store_code TEXT NOT NULL,
  qty_on_hand INTEGER NOT NULL DEFAULT 0,
  qty_on_order INTEGER DEFAULT 0,
  qty_reserved INTEGER DEFAULT 0,
  bin_location TEXT,
  last_counted_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, product_id, store_code)
);

-- ── Sales ──────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,   -- human-facing receipt #
  store_code TEXT,
  customer_id UUID REFERENCES pos.customers(id),
  employee_id TEXT,                   -- selling rep (storeops employee_id)
  receipt_type TEXT DEFAULT 'sale',
  status TEXT DEFAULT 'completed' CHECK (status IN ('completed','voided')),
  subtotal NUMERIC(12,2) DEFAULT 0,   -- net of line discounts, tax-exclusive
  discount_total NUMERIC(12,2) DEFAULT 0,
  tax_total NUMERIC(12,2) DEFAULT 0,
  total NUMERIC(12,2) DEFAULT 0,      -- subtotal + tax_total
  balance NUMERIC(12,2) DEFAULT 0,
  is_activation_sale BOOLEAN DEFAULT false,
  receipt JSONB,                      -- full receipt snapshot at checkout (incl. tendered/change)
  voided_at TIMESTAMPTZ,
  voided_by TEXT,                     -- employee_id who voided
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, transaction_id)
);
CREATE INDEX IF NOT EXISTS pos_sales_org_created ON pos.sales(org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS pos_sales_store ON pos.sales(org_id, store_code, created_at DESC);

CREATE TABLE IF NOT EXISTS pos.sale_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  sale_id UUID NOT NULL REFERENCES pos.sales(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES pos.products(id),
  product_type TEXT,
  description TEXT,
  serial_number TEXT,                 -- non-empty ⇒ serial-tracked unit; drives the inventory trigger branch
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price NUMERIC(12,2) NOT NULL,
  cost NUMERIC(12,2),                 -- snapshot of products.cost (cost_based tax)
  discount NUMERIC(12,2) DEFAULT 0,   -- per unit
  tax_rate NUMERIC(8,6) DEFAULT 0,    -- FRACTION (0.08875), not percent
  tax_value NUMERIC(12,2) DEFAULT 0,  -- line level: per-unit tax × qty
  extended_price NUMERIC(12,2) NOT NULL,  -- (unit_price − discount + per_unit_tax) × qty (tax-inclusive)
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_sale_items_sale ON pos.sale_items(sale_id);

CREATE TABLE IF NOT EXISTS pos.sale_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  sale_id UUID NOT NULL REFERENCES pos.sales(id) ON DELETE CASCADE,
  payment_method TEXT NOT NULL
    CHECK (payment_method IN ('cash','credit_card','debit_card','check','card_external')),
  amount NUMERIC(12,2) NOT NULL,
  card_last_four TEXT,
  check_number TEXT,
  emv_status TEXT,
  processor TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_sale_payments_sale ON pos.sale_payments(sale_id);

-- inventory_serial.sold_in_sale_id → sales (deferred: sales is defined after inventory_serial)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pos_inv_serial_sold_sale_fk') THEN
    ALTER TABLE pos.inventory_serial
      ADD CONSTRAINT pos_inv_serial_sold_sale_fk
      FOREIGN KEY (sold_in_sale_id) REFERENCES pos.sales(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ── Tax codes ──────────────────────────────────────────────────────────────────────────────────────
-- rate is a PERCENT (8.875); pos.sale_items.tax_rate stores the fraction. The register resolves:
-- active code for the store → active org-wide code (store_code null) → none (0 tax + warning chip).
CREATE TABLE IF NOT EXISTS pos.tax_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  name TEXT NOT NULL,
  rate NUMERIC(6,3) NOT NULL CHECK (rate >= 0 AND rate <= 30),
  store_code TEXT,                    -- null = org-wide fallback
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_tax_codes_org ON pos.tax_codes(org_id, is_active);

-- ── Receipt templates ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.receipt_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  name TEXT NOT NULL DEFAULT 'Default',
  carrier TEXT,                       -- null = org default; set = carrier-specific format
  is_default BOOLEAN NOT NULL DEFAULT false,
  header_text TEXT,
  footer_text TEXT NOT NULL DEFAULT 'Thank you for your business!',
  show_store_name BOOLEAN NOT NULL DEFAULT true,
  show_customer BOOLEAN NOT NULL DEFAULT true,
  show_employee BOOLEAN NOT NULL DEFAULT false,
  show_serials BOOLEAN NOT NULL DEFAULT true,
  show_tax_breakdown BOOLEAN NOT NULL DEFAULT true,
  show_discounts BOOLEAN NOT NULL DEFAULT true,
  paper_width_mm INTEGER NOT NULL DEFAULT 80 CHECK (paper_width_mm IN (58, 80)),
  font_size_px INTEGER NOT NULL DEFAULT 12 CHECK (font_size_px BETWEEN 9 AND 16),
  sample_image_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS pos_receipt_templates_one_default
  ON pos.receipt_templates (org_id) WHERE is_default;
CREATE UNIQUE INDEX IF NOT EXISTS pos_receipt_templates_org_carrier
  ON pos.receipt_templates (org_id, lower(carrier)) WHERE carrier IS NOT NULL;

-- ── POS settings kv (config engine) ────────────────────────────────────────────────────────────────
-- One jsonb value per key: org default (store_code null) or per-store override. Effective value =
-- store override ?? org default ?? code-side default (frontend/src/lib/pos-config.ts registry).
CREATE TABLE IF NOT EXISTS pos.pos_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  store_code TEXT,                    -- null = org-level default row
  key TEXT NOT NULL,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS pos_settings_org_key
  ON pos.pos_settings (org_id, key) WHERE store_code IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS pos_settings_store_key
  ON pos.pos_settings (org_id, store_code, key) WHERE store_code IS NOT NULL;

-- Effective value for one key: store override → org default → null (caller falls back to the
-- code-side default).
CREATE OR REPLACE FUNCTION pos.pos_setting(p_org UUID, p_store TEXT, p_key TEXT)
RETURNS JSONB
LANGUAGE sql
STABLE
SET search_path = pos, pg_temp
AS $$
  SELECT value FROM (
    SELECT value, 1 AS pri FROM pos.pos_settings
      WHERE org_id = p_org AND store_code = p_store AND p_store IS NOT NULL AND key = p_key
    UNION ALL
    SELECT value, 2 FROM pos.pos_settings
      WHERE org_id = p_org AND store_code IS NULL AND key = p_key
  ) v ORDER BY pri LIMIT 1;
$$;

-- ── Register (cash drawer) sessions ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.register_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  store_code TEXT NOT NULL,
  register_number INT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  opened_by TEXT,                     -- employee_id
  opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  opening_float NUMERIC(10,2) NOT NULL DEFAULT 0,
  opening_denominations JSONB,
  closed_by TEXT,                     -- employee_id
  closed_at TIMESTAMPTZ,
  closing_counted NUMERIC(10,2),
  closing_expected NUMERIC(10,2),
  variance NUMERIC(10,2),
  closing_denominations JSONB,
  notes TEXT
);
CREATE INDEX IF NOT EXISTS pos_register_sessions_org_store
  ON pos.register_sessions (org_id, store_code, opened_at DESC);
-- Only one open session per store register at a time.
CREATE UNIQUE INDEX IF NOT EXISTS pos_register_sessions_one_open
  ON pos.register_sessions (org_id, store_code, register_number) WHERE status = 'open';

CREATE OR REPLACE FUNCTION pos.open_register(
  p_org UUID,
  p_store TEXT,
  p_register INT DEFAULT 1,
  p_employee TEXT DEFAULT NULL,
  p_float NUMERIC DEFAULT 0,
  p_denominations JSONB DEFAULT NULL
)
RETURNS pos.register_sessions
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  v_row pos.register_sessions;
BEGIN
  IF p_org IS NULL OR p_store IS NULL OR btrim(p_store) = '' THEN
    RAISE EXCEPTION 'org and store are required';
  END IF;
  IF p_float IS NULL OR p_float < 0 THEN
    RAISE EXCEPTION 'opening float must be zero or more';
  END IF;

  INSERT INTO pos.register_sessions
    (org_id, store_code, register_number, opened_by, opening_float, opening_denominations)
  VALUES (p_org, p_store, COALESCE(p_register, 1), NULLIF(btrim(COALESCE(p_employee, '')), ''),
          p_float, p_denominations)
  RETURNING * INTO v_row;
  RETURN v_row;
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION 'register % at this store is already open — close it first', COALESCE(p_register, 1);
END;
$$;

-- Close: expected cash = opening float + cash payments on non-voided sales at this store since
-- open. Variance = counted − expected, computed HERE (the client never computes expected).
CREATE OR REPLACE FUNCTION pos.close_register(
  p_org UUID,
  p_session UUID,
  p_counted NUMERIC,
  p_employee TEXT DEFAULT NULL,
  p_denominations JSONB DEFAULT NULL,
  p_notes TEXT DEFAULT NULL
)
RETURNS pos.register_sessions
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  s pos.register_sessions;
  v_cash NUMERIC;
  v_expected NUMERIC;
BEGIN
  SELECT * INTO s FROM pos.register_sessions WHERE id = p_session AND org_id = p_org;
  IF s.id IS NULL THEN
    RAISE EXCEPTION 'register session not found';
  END IF;
  IF s.status <> 'open' THEN
    RAISE EXCEPTION 'this register session is already closed';
  END IF;
  IF p_counted IS NULL OR p_counted < 0 THEN
    RAISE EXCEPTION 'counted cash must be zero or more';
  END IF;

  SELECT COALESCE(SUM(sp.amount), 0) INTO v_cash
  FROM pos.sale_payments sp
  JOIN pos.sales sa ON sa.id = sp.sale_id
  WHERE sa.org_id = s.org_id
    AND sa.store_code = s.store_code
    AND sa.created_at >= s.opened_at
    AND COALESCE(sa.status, 'completed') <> 'voided'
    AND sp.payment_method = 'cash';

  v_expected := s.opening_float + v_cash;

  UPDATE pos.register_sessions
     SET status = 'closed',
         closed_by = NULLIF(btrim(COALESCE(p_employee, '')), ''),
         closed_at = NOW(),
         closing_counted = p_counted,
         closing_expected = v_expected,
         variance = p_counted - v_expected,
         closing_denominations = p_denominations,
         notes = p_notes
   WHERE id = p_session
   RETURNING * INTO s;
  RETURN s;
END;
$$;

-- ── Inventory movement on checkout ─────────────────────────────────────────────────────────────────
-- AFTER INSERT trigger on sale_items: same transaction as the item insert, so a failed movement
-- can never half-apply. Serial items flip to 'sold'; standard items decrement the store's count.
-- Honors the 'allow_negative_inventory' setting (blocks below-zero sales when off).
CREATE OR REPLACE FUNCTION pos.apply_sale_item_inventory()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  v_store TEXT;
  v_allow BOOLEAN;
  v_on_hand NUMERIC;
BEGIN
  SELECT s.store_code INTO v_store FROM pos.sales s WHERE s.id = NEW.sale_id;

  IF NEW.serial_number IS NOT NULL AND btrim(NEW.serial_number) <> '' THEN
    UPDATE pos.inventory_serial i
       SET status = 'sold', sold_at = NOW(), sold_in_sale_id = NEW.sale_id, updated_at = NOW()
     WHERE i.org_id = NEW.org_id
       AND i.serial_number = NEW.serial_number
       AND i.status IN ('in_stock', 'in_transit');
    -- not found ⇒ unit wasn't tracked; the sale proceeds (serials aren't validated at the register)
  ELSIF v_store IS NOT NULL THEN
    v_allow := COALESCE((pos.pos_setting(NEW.org_id, v_store, 'allow_negative_inventory') #>> '{}')::boolean, true);
    IF NOT v_allow THEN
      SELECT st.qty_on_hand INTO v_on_hand FROM pos.inventory_standard st
       WHERE st.org_id = NEW.org_id AND st.product_id = NEW.product_id AND st.store_code = v_store;
      IF COALESCE(v_on_hand, 0) - COALESCE(NEW.qty, 0) < 0 THEN
        RAISE EXCEPTION 'Not enough stock for "%" (% on hand) — selling below zero is disabled in POS Settings.',
          COALESCE(NEW.description, 'item'), COALESCE(v_on_hand, 0);
      END IF;
    END IF;
    UPDATE pos.inventory_standard st
       SET qty_on_hand = st.qty_on_hand - COALESCE(NEW.qty, 0), updated_at = NOW()
     WHERE st.org_id = NEW.org_id
       AND st.product_id = NEW.product_id
       AND st.store_code = v_store;
    -- negative quantities allowed by default: they surface count discrepancies instead of
    -- blocking a real cash sale.
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS apply_sale_item_inventory ON pos.sale_items;
CREATE TRIGGER apply_sale_item_inventory
  AFTER INSERT ON pos.sale_items
  FOR EACH ROW EXECUTE FUNCTION pos.apply_sale_item_inventory();

-- ── Atomic checkout ────────────────────────────────────────────────────────────────────────────────
-- One call inserts the sale + items + payments in a single transaction (the standalone app's three
-- client round-trips could strand a header-only sale). Item inserts fire the inventory trigger.
-- p_sale: {store_code, customer_id, employee_id, receipt_type, subtotal, discount_total, tax_total,
--          total, balance, is_activation_sale, receipt, notes}
-- p_items: [{product_id, product_type, description, serial_number, qty, unit_price, cost, discount,
--            tax_rate, tax_value, extended_price}]
-- p_payments: [{payment_method, amount, card_last_four, check_number}]
CREATE OR REPLACE FUNCTION pos.checkout(
  p_org UUID,
  p_sale JSONB,
  p_items JSONB,
  p_payments JSONB
)
RETURNS pos.sales
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  v_sale pos.sales;
  it JSONB;
  pay JSONB;
BEGIN
  IF p_org IS NULL THEN
    RAISE EXCEPTION 'org is required';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'a sale needs at least one item';
  END IF;

  INSERT INTO pos.sales (org_id, store_code, customer_id, employee_id, receipt_type, status,
                         subtotal, discount_total, tax_total, total, balance, is_activation_sale,
                         receipt, notes)
  VALUES (
    p_org,
    NULLIF(btrim(COALESCE(p_sale->>'store_code', '')), ''),
    NULLIF(p_sale->>'customer_id', '')::uuid,
    NULLIF(btrim(COALESCE(p_sale->>'employee_id', '')), ''),
    COALESCE(NULLIF(p_sale->>'receipt_type', ''), 'sale'),
    'completed',
    COALESCE((p_sale->>'subtotal')::numeric, 0),
    COALESCE((p_sale->>'discount_total')::numeric, 0),
    COALESCE((p_sale->>'tax_total')::numeric, 0),
    COALESCE((p_sale->>'total')::numeric, 0),
    COALESCE((p_sale->>'balance')::numeric, 0),
    COALESCE((p_sale->>'is_activation_sale')::boolean, false),
    p_sale->'receipt',
    NULLIF(p_sale->>'notes', '')
  )
  RETURNING * INTO v_sale;

  FOR it IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO pos.sale_items (org_id, sale_id, product_id, product_type, description,
                                serial_number, qty, unit_price, cost, discount, tax_rate,
                                tax_value, extended_price)
    VALUES (
      p_org, v_sale.id,
      (it->>'product_id')::uuid,
      NULLIF(it->>'product_type', ''),
      NULLIF(it->>'description', ''),
      NULLIF(btrim(COALESCE(it->>'serial_number', '')), ''),
      COALESCE((it->>'qty')::int, 1),
      COALESCE((it->>'unit_price')::numeric, 0),
      (it->>'cost')::numeric,
      COALESCE((it->>'discount')::numeric, 0),
      COALESCE((it->>'tax_rate')::numeric, 0),
      COALESCE((it->>'tax_value')::numeric, 0),
      COALESCE((it->>'extended_price')::numeric, 0)
    );
  END LOOP;

  IF p_payments IS NOT NULL AND jsonb_typeof(p_payments) = 'array' THEN
    FOR pay IN SELECT * FROM jsonb_array_elements(p_payments) LOOP
      INSERT INTO pos.sale_payments (org_id, sale_id, payment_method, amount,
                                     card_last_four, check_number)
      VALUES (
        p_org, v_sale.id,
        pay->>'payment_method',
        COALESCE((pay->>'amount')::numeric, 0),
        NULLIF(pay->>'card_last_four', ''),
        NULLIF(pay->>'check_number', '')
      );
    END LOOP;
  END IF;

  RETURN v_sale;
END;
$$;

-- ── Void: atomic reversal ──────────────────────────────────────────────────────────────────────────
-- RBAC (who may void) is enforced in the FastAPI layer; this function only does the mechanics.
CREATE OR REPLACE FUNCTION pos.void_sale(p_org UUID, p_sale UUID, p_employee TEXT DEFAULT NULL)
RETURNS pos.sales
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  s pos.sales;
  it RECORD;
BEGIN
  SELECT * INTO s FROM pos.sales WHERE id = p_sale AND org_id = p_org;
  IF s.id IS NULL THEN
    RAISE EXCEPTION 'sale not found';
  END IF;
  IF s.status = 'voided' OR s.voided_at IS NOT NULL THEN
    RAISE EXCEPTION 'transaction #% is already voided', s.transaction_id;
  END IF;

  FOR it IN SELECT * FROM pos.sale_items WHERE sale_id = p_sale LOOP
    IF it.serial_number IS NOT NULL AND btrim(it.serial_number) <> '' THEN
      UPDATE pos.inventory_serial i
         SET status = 'in_stock', sold_at = NULL, sold_in_sale_id = NULL, updated_at = NOW()
       WHERE i.org_id = s.org_id
         AND i.serial_number = it.serial_number
         AND i.sold_in_sale_id = p_sale;
    ELSIF s.store_code IS NOT NULL THEN
      UPDATE pos.inventory_standard st
         SET qty_on_hand = st.qty_on_hand + COALESCE(it.qty, 0), updated_at = NOW()
       WHERE st.org_id = s.org_id
         AND st.product_id = it.product_id
         AND st.store_code = s.store_code;
    END IF;
  END LOOP;

  UPDATE pos.sales
     SET status = 'voided', voided_at = NOW(),
         voided_by = NULLIF(btrim(COALESCE(p_employee, '')), ''),
         updated_at = NOW()
   WHERE id = p_sale
   RETURNING * INTO s;
  RETURN s;
END;
$$;

-- ── PII encryption (Vault + pgcrypto) ──────────────────────────────────────────────────────────────
-- Same design as the standalone app's 20260806090003: key lives in Vault, never in a table or in
-- application code; the database holds ciphertext only. Differences: functions take an explicit
-- p_org (no auth.uid() — the backend is the only caller) and WHO may read full PII is a FastAPI
-- RBAC decision. The org check here is the belt-and-suspenders tenancy guard.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM vault.secrets WHERE name = 'pos_pii_encryption_key') THEN
    PERFORM vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'pos_pii_encryption_key',
      'Symmetric key for pos.customers PII columns (pgp_sym_encrypt); do not delete or rotate without re-encrypting ssn_enc / driver_license_enc'
    );
  END IF;
END $$;

-- The ONLY reader of the vault secret. SECURITY DEFINER to read vault.decrypted_secrets;
-- EXECUTE revoked from every client role below (the sibling definer functions are the only
-- callers — the function owner always has EXECUTE on its own functions).
CREATE OR REPLACE FUNCTION pos.pii_key()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pos, pg_temp
AS $$
  SELECT ds.decrypted_secret
  FROM vault.decrypted_secrets ds
  WHERE ds.name = 'pos_pii_encryption_key';
$$;
REVOKE ALL ON FUNCTION pos.pii_key() FROM public, anon, authenticated;

CREATE OR REPLACE FUNCTION pos.customer_pii_set(
  p_org UUID,
  p_customer UUID,
  p_ssn TEXT,
  p_driver_license TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pos, pg_temp
AS $$
DECLARE
  k TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pos.customers c WHERE c.id = p_customer AND c.org_id = p_org) THEN
    RAISE EXCEPTION 'customer not found';
  END IF;
  k := pos.pii_key();
  -- PER-COLUMN semantics (owner constraint 2026-08-08: nothing may delete what it did not
  -- write). Previously BOTH columns were rewritten on every call, so saving only a driver
  -- licence NULLed the SSN ciphertext — and the plaintext exists nowhere else, so that loss
  -- was irreversible. Now:
  --   p_* IS NULL       ⇒ field omitted by the caller ⇒ leave the stored value untouched
  --   p_* = '' (blank)  ⇒ caller explicitly cleared the field ⇒ set NULL
  --   otherwise         ⇒ encrypt and store
  -- The omission case is the common one, so it is the one that must be safe by default.
  UPDATE pos.customers c
     SET ssn_enc = CASE
                     WHEN p_ssn IS NULL THEN c.ssn_enc
                     WHEN btrim(p_ssn) = '' THEN NULL
                     ELSE extensions.pgp_sym_encrypt(btrim(p_ssn), k)
                   END,
         driver_license_enc = CASE
                     WHEN p_driver_license IS NULL THEN c.driver_license_enc
                     WHEN btrim(p_driver_license) = '' THEN NULL
                     ELSE extensions.pgp_sym_encrypt(btrim(p_driver_license), k)
                   END,
         updated_at = NOW()
   WHERE c.id = p_customer;
END;
$$;
REVOKE ALL ON FUNCTION pos.customer_pii_set(UUID, UUID, TEXT, TEXT) FROM public, anon, authenticated;

CREATE OR REPLACE FUNCTION pos.customer_pii_get(p_org UUID, p_customer UUID)
RETURNS TABLE (ssn TEXT, driver_license_num TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pos, pg_temp
AS $$
DECLARE
  k TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pos.customers c WHERE c.id = p_customer AND c.org_id = p_org) THEN
    RAISE EXCEPTION 'customer not found';
  END IF;
  k := pos.pii_key();
  RETURN QUERY
  SELECT
    CASE WHEN c.ssn_enc            IS NULL THEN NULL
         ELSE extensions.pgp_sym_decrypt(c.ssn_enc, k) END,
    CASE WHEN c.driver_license_enc IS NULL THEN NULL
         ELSE extensions.pgp_sym_decrypt(c.driver_license_enc, k) END
  FROM pos.customers c
  WHERE c.id = p_customer;
END;
$$;
REVOKE ALL ON FUNCTION pos.customer_pii_get(UUID, UUID) FROM public, anon, authenticated;

CREATE OR REPLACE FUNCTION pos.customer_pii_last4(p_org UUID, p_customer UUID)
RETURNS TABLE (ssn_last4 TEXT, dl_last4 TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pos, pg_temp
AS $$
DECLARE
  k TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pos.customers c WHERE c.id = p_customer AND c.org_id = p_org) THEN
    RAISE EXCEPTION 'customer not found';
  END IF;
  k := pos.pii_key();
  RETURN QUERY
  SELECT
    CASE WHEN c.ssn_enc            IS NULL THEN NULL
         ELSE right(extensions.pgp_sym_decrypt(c.ssn_enc, k), 4) END,
    CASE WHEN c.driver_license_enc IS NULL THEN NULL
         ELSE right(extensions.pgp_sym_decrypt(c.driver_license_enc, k), 4) END
  FROM pos.customers c
  WHERE c.id = p_customer;
END;
$$;
REVOKE ALL ON FUNCTION pos.customer_pii_last4(UUID, UUID) FROM public, anon, authenticated;

-- ── Security: re-assert the 722-style lockdown over the WHOLE pos schema ───────────────────────────
-- (Same block as mig 724 — idempotent; picks up every table/function added by this migration.
-- Backend-only access: service_role bypasses RLS; anon/authenticated get nothing.)
DO $$
DECLARE t RECORD;
BEGIN
  EXECUTE 'GRANT USAGE ON SCHEMA pos TO service_role';
  EXECUTE 'REVOKE ALL ON SCHEMA pos FROM anon, authenticated';
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'pos' LOOP
    EXECUTE format('ALTER TABLE pos.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  EXECUTE 'REVOKE ALL ON ALL TABLES    IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'GRANT ALL ON ALL TABLES    IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA pos TO service_role';
END $$;
-- pos.pii_key must stay callable ONLY from inside the sibling definer functions.
REVOKE ALL ON FUNCTION pos.pii_key() FROM service_role;
