-- MIGRATION 726: POS MODULE — PHASE 2: ACTIVATIONS, VENDORS, PURCHASE ORDERS, TRANSFERS
-- Run this in the Supabase SQL editor (after 725). Idempotent.
--
-- Ports the rest of the standalone pos-system app's data model into pos.*:
--   activations (+ service plans catalog, dealer codes, carrier credit-check portals,
--   activation notes, trade-ins), vendors, purchase orders (+ items, unused by the UI yet
--   but kept for the receiving flow to come), store-to-store transfers with ATOMIC
--   create/ship/receive functions (ship/receive port the standalone RPCs; create is new —
--   the old app did a 2-step client insert with manual rollback).
--
-- Identity conventions (same as 724/725): org_id UUID on every row; stores by
-- storeops.stores.store_code TEXT; employees by storeops.employees.employee_id TEXT;
-- no auth.uid() — RBAC lives in the FastAPI layer.

CREATE SCHEMA IF NOT EXISTS pos;

-- ── Service plans catalog ──────────────────────────────────────────────────────────────────────────
-- Ships empty (owner still owes the carriers/plans/fees list — QUESTIONS.md); the activation
-- form's plan dropdown reads it and auto-fills fee/contract fields.
CREATE TABLE IF NOT EXISTS pos.service_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  carrier TEXT NOT NULL,
  plan_code TEXT,
  plan_name TEXT NOT NULL,
  plan_description TEXT,
  monthly_fee NUMERIC(10,2),
  included_minutes INTEGER,
  service_area TEXT,
  contract_type TEXT,
  contract_terms TEXT,
  dealer_code TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_service_plans_org ON pos.service_plans(org_id, carrier);

-- ── Dealer codes (assignable managed list) ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.dealer_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  code TEXT NOT NULL,
  carrier TEXT,
  store_code TEXT,                    -- null = org-wide
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (org_id, code)
);

-- ── Carrier credit-check / web portal quick links ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.carrier_portals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  carrier TEXT NOT NULL,
  url TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS pos_carrier_portals_org_carrier
  ON pos.carrier_portals (org_id, carrier);

-- ── Activations ────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.activations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  activation_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  sale_id UUID REFERENCES pos.sales(id) ON DELETE SET NULL,
  customer_id UUID REFERENCES pos.customers(id) ON DELETE SET NULL,
  store_code TEXT,
  employee_id TEXT,                   -- selling rep (storeops employee_id)
  carrier TEXT,
  activation_date DATE,
  service_plan_date DATE,
  service_plan_id UUID REFERENCES pos.service_plans(id) ON DELETE SET NULL,
  plan_code TEXT,
  plan_description TEXT,
  monthly_fee NUMERIC(10,2),
  included_minutes INTEGER,
  service_area TEXT,
  contract_type TEXT,
  contract_terms TEXT,
  dealer_code TEXT,
  cell_number TEXT,
  phone_serial TEXT,
  phone_model TEXT,
  sim_card TEXT,
  mobile_phone TEXT,                  -- mirrors cell_number (owner: one field, write both)
  account_number TEXT,
  deposit_amount NUMERIC(10,2) DEFAULT 0,
  memo TEXT,
  description TEXT,
  notes TEXT,                         -- free-text column written only by CSV import
  promotion_offered TEXT,
  trade_in_credit NUMERIC(10,2),
  special_promo TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','cancelled','transferred')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, activation_number)
);
CREATE INDEX IF NOT EXISTS pos_activations_org_date ON pos.activations(org_id, activation_date DESC);
-- the default list view orders by created_at DESC with no date filter
CREATE INDEX IF NOT EXISTS pos_activations_org_created ON pos.activations(org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS pos_activations_customer ON pos.activations(customer_id);
CREATE INDEX IF NOT EXISTS pos_activations_cell ON pos.activations(org_id, cell_number);
-- inventory list: filter by store, newest first
CREATE INDEX IF NOT EXISTS pos_inv_serial_store ON pos.inventory_serial(org_id, store_code, created_at DESC);

CREATE TABLE IF NOT EXISTS pos.activation_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  activation_id UUID NOT NULL REFERENCES pos.activations(id) ON DELETE CASCADE,
  employee_id TEXT,
  note TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'normal' CHECK (severity IN ('normal','important','urgent')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_activation_notes_act
  ON pos.activation_notes(activation_id, created_at DESC);

-- ── Trade-ins (device in, credit out, sent-back tracking) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.trade_ins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  activation_id UUID REFERENCES pos.activations(id) ON DELETE SET NULL,
  sale_id UUID REFERENCES pos.sales(id) ON DELETE SET NULL,
  customer_id UUID REFERENCES pos.customers(id) ON DELETE SET NULL,
  device_description TEXT NOT NULL,
  serial_number TEXT,
  imei TEXT,
  credit_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received','sent_back','written_off')),
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_back_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_trade_ins_org_status ON pos.trade_ins(org_id, status);
CREATE INDEX IF NOT EXISTS pos_trade_ins_activation ON pos.trade_ins(activation_id);

-- ── Vendors ────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.vendors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  ban TEXT,
  legal_name TEXT NOT NULL,
  short_name TEXT,
  business_type TEXT DEFAULT 'Vendor',
  street_one TEXT,
  street_two TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  country TEXT DEFAULT 'USA',
  tax_id TEXT,
  contact_name TEXT,
  phone TEXT,
  fax TEXT,
  email TEXT,
  website TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_vendors_org ON pos.vendors(org_id, is_active);

-- ── Purchase orders ────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  po_number TEXT NOT NULL,
  vendor_id UUID NOT NULL REFERENCES pos.vendors(id),
  store_code TEXT,
  created_by TEXT,                    -- employee_id
  status TEXT DEFAULT 'draft',
  order_date DATE,
  expected_date DATE,
  received_date DATE,
  notes TEXT,
  total_cost NUMERIC(12,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, po_number)
);

-- Line items: the standalone UI never wrote these; kept so the receiving flow can land
-- without another migration.
CREATE TABLE IF NOT EXISTS pos.purchase_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  po_id UUID NOT NULL REFERENCES pos.purchase_orders(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES pos.products(id),
  qty_ordered INTEGER NOT NULL,
  qty_received INTEGER DEFAULT 0,
  unit_cost NUMERIC(12,2),
  serial_numbers TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Store-to-store transfers ───────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pos.store_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  transfer_number TEXT NOT NULL,
  from_store_code TEXT NOT NULL,
  to_store_code TEXT NOT NULL,
  created_by TEXT,                    -- employee_id
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','shipped','received','cancelled')),
  shipped_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, transfer_number)
);

CREATE TABLE IF NOT EXISTS pos.store_transfer_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL,
  transfer_id UUID NOT NULL REFERENCES pos.store_transfers(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES pos.products(id),
  qty INTEGER,
  serial_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pos_transfer_items_transfer
  ON pos.store_transfer_items(transfer_id);

-- Atomic create: header + items in one transaction (the standalone app inserted the header,
-- then the items, deleting the header by hand when the items failed).
-- p_header: {transfer_number, from_store_code, to_store_code, created_by, notes}
-- p_items:  [{product_id, qty, serial_number}]
CREATE OR REPLACE FUNCTION pos.create_transfer(p_org UUID, p_header JSONB, p_items JSONB)
RETURNS pos.store_transfers
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  v_row pos.store_transfers;
  it JSONB;
BEGIN
  IF p_org IS NULL THEN
    RAISE EXCEPTION 'org is required';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'a transfer needs at least one item';
  END IF;
  IF NULLIF(btrim(COALESCE(p_header->>'from_store_code', '')), '') IS NULL
     OR NULLIF(btrim(COALESCE(p_header->>'to_store_code', '')), '') IS NULL THEN
    RAISE EXCEPTION 'source and destination stores are required';
  END IF;
  IF (p_header->>'from_store_code') = (p_header->>'to_store_code') THEN
    RAISE EXCEPTION 'source and destination must be different stores';
  END IF;

  INSERT INTO pos.store_transfers (org_id, transfer_number, from_store_code, to_store_code,
                                   created_by, status, notes)
  VALUES (
    p_org,
    p_header->>'transfer_number',
    p_header->>'from_store_code',
    p_header->>'to_store_code',
    NULLIF(btrim(COALESCE(p_header->>'created_by', '')), ''),
    'pending',
    NULLIF(p_header->>'notes', '')
  )
  RETURNING * INTO v_row;

  FOR it IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO pos.store_transfer_items (org_id, transfer_id, product_id, qty, serial_number)
    VALUES (
      p_org, v_row.id,
      (it->>'product_id')::uuid,
      COALESCE((it->>'qty')::int, 1),
      NULLIF(btrim(COALESCE(it->>'serial_number', '')), '')
    );
  END LOOP;

  RETURN v_row;
END;
$$;

-- Ship: serials flip to in_transit, standard stock decrements at the source (with a FOR UPDATE
-- stock check). Ported from the standalone ship_transfer RPC; RBAC moved to the FastAPI layer.
CREATE OR REPLACE FUNCTION pos.ship_transfer(p_org UUID, p_transfer UUID)
RETURNS pos.store_transfers
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  t pos.store_transfers;
  it RECORD;
  v_have INTEGER;
BEGIN
  SELECT * INTO t FROM pos.store_transfers WHERE id = p_transfer AND org_id = p_org;
  IF t.id IS NULL THEN
    RAISE EXCEPTION 'transfer not found';
  END IF;
  IF t.status IS DISTINCT FROM 'pending' THEN
    RAISE EXCEPTION 'transfer % is %, only pending transfers can ship', t.transfer_number, t.status;
  END IF;

  FOR it IN SELECT * FROM pos.store_transfer_items WHERE transfer_id = p_transfer LOOP
    IF it.serial_number IS NOT NULL AND btrim(it.serial_number) <> '' THEN
      UPDATE pos.inventory_serial s
         SET status = 'in_transit', updated_at = NOW()
       WHERE s.org_id = t.org_id
         AND s.serial_number = it.serial_number
         AND s.store_code = t.from_store_code
         AND s.status = 'in_stock';
      IF NOT FOUND THEN
        RAISE EXCEPTION 'serial % is not in stock at the source store', it.serial_number;
      END IF;
    ELSE
      SELECT qty_on_hand INTO v_have
      FROM pos.inventory_standard
      WHERE org_id = t.org_id AND product_id = it.product_id
        AND store_code = t.from_store_code
      FOR UPDATE;
      IF COALESCE(v_have, 0) < COALESCE(it.qty, 0) THEN
        RAISE EXCEPTION 'insufficient stock to ship % units (have %)', it.qty, COALESCE(v_have, 0);
      END IF;
      UPDATE pos.inventory_standard
         SET qty_on_hand = qty_on_hand - it.qty, updated_at = NOW()
       WHERE org_id = t.org_id AND product_id = it.product_id
         AND store_code = t.from_store_code;
    END IF;
  END LOOP;

  UPDATE pos.store_transfers
     SET status = 'shipped', shipped_at = NOW()
   WHERE id = p_transfer
   RETURNING * INTO t;
  RETURN t;
END;
$$;

-- Receive: serials land in_stock at the destination, standard stock upserts. Ported from the
-- standalone receive_transfer RPC.
CREATE OR REPLACE FUNCTION pos.receive_transfer(p_org UUID, p_transfer UUID)
RETURNS pos.store_transfers
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  t pos.store_transfers;
  it RECORD;
BEGIN
  SELECT * INTO t FROM pos.store_transfers WHERE id = p_transfer AND org_id = p_org;
  IF t.id IS NULL THEN
    RAISE EXCEPTION 'transfer not found';
  END IF;
  IF t.status IS DISTINCT FROM 'shipped' THEN
    RAISE EXCEPTION 'transfer % is %, only shipped transfers can be received', t.transfer_number, t.status;
  END IF;

  FOR it IN SELECT * FROM pos.store_transfer_items WHERE transfer_id = p_transfer LOOP
    IF it.serial_number IS NOT NULL AND btrim(it.serial_number) <> '' THEN
      UPDATE pos.inventory_serial s
         SET status = 'in_stock', store_code = t.to_store_code, updated_at = NOW()
       WHERE s.org_id = t.org_id
         AND s.serial_number = it.serial_number
         AND s.status = 'in_transit';
      IF NOT FOUND THEN
        RAISE EXCEPTION 'serial % is not in transit on this transfer', it.serial_number;
      END IF;
    ELSE
      INSERT INTO pos.inventory_standard (org_id, product_id, store_code, qty_on_hand)
      VALUES (t.org_id, it.product_id, t.to_store_code, it.qty)
      ON CONFLICT (org_id, product_id, store_code)
      DO UPDATE SET qty_on_hand = pos.inventory_standard.qty_on_hand + EXCLUDED.qty_on_hand,
                    updated_at = NOW();
    END IF;
  END LOOP;

  UPDATE pos.store_transfers
     SET status = 'received', received_at = NOW()
   WHERE id = p_transfer
   RETURNING * INTO t;
  RETURN t;
END;
$$;

-- ── Security: re-assert the 722-style lockdown over the WHOLE pos schema ───────────────────────────
-- (Same block as 724/725 — idempotent; picks up every table/function added here.)
DO $$
DECLARE t RECORD;
BEGIN
  EXECUTE 'GRANT USAGE ON SCHEMA pos TO service_role';
  EXECUTE 'REVOKE ALL ON SCHEMA pos FROM anon, authenticated';
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'pos' LOOP
    EXECUTE format('ALTER TABLE pos.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
  EXECUTE 'REVOKE ALL ON ALL TABLES    IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA pos FROM anon, authenticated';
  EXECUTE 'GRANT ALL ON ALL TABLES    IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA pos TO service_role';
  EXECUTE 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA pos TO service_role';
END $$;
-- pos.pii_key (mig 725) must stay callable ONLY from inside its sibling definer functions.
REVOKE ALL ON FUNCTION pos.pii_key() FROM service_role;
