-- 865_pos_special_orders.sql — POS "Customer Special Order" (owner directive 2026-08-19), Phase 2:
-- the special-order record itself. See docs/POS_SPECIAL_ORDER_PLAN.md.
--
-- One row per customer special order. It links the booked POS sale (pos.sales) — which is what makes
-- the declared sale value a SALE, the captured vendor cost the COGS, and the difference PROFIT (all
-- derived by the accounting engine, no new money plumbing) — to the fulfillment lifecycle (ordered →
-- shipped → received → delivered) and, HQ-side, to the hidden vendor order (Amazon).
--
-- Single-line for now (a customer special-orders one item); multi-line can be added later. Org-scoped
-- per the migration-728 tenant-scoped-FK convention. Additive + idempotent. pos.* is service-role-only.
CREATE TABLE IF NOT EXISTS pos.special_orders (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            uuid NOT NULL,
  order_no          bigint GENERATED BY DEFAULT AS IDENTITY,   -- human-friendly reference
  store_code        text NOT NULL,                 -- selling store
  ship_to_store     text,                           -- where it ships (defaults to store_code)
  customer_id       uuid,                           -- pos.customers (optional; plain col — no FK)
  customer_name     text,                           -- display fallback when no customer record
  employee_id       text,                           -- selling rep (from the login, never a body field)
  product_id        uuid NOT NULL,                  -- the special-order catalog product
  description       text,                           -- product name snapshot
  qty               numeric NOT NULL DEFAULT 1,
  sale_price        numeric NOT NULL,               -- declared UNIT sale price at order time
  captured_cost     numeric,                        -- vendor unit cost at order time (COGS basis)
  actual_cost       numeric,                        -- trued-up unit cost once the real order is placed
  sale_id           uuid,                           -- the booked pos.sales row (plain col — no FK)
  status            text NOT NULL DEFAULT 'ordered'
                    CHECK (status IN ('requested','ordered','shipped','received','delivered','cancelled')),
  vendor            text NOT NULL DEFAULT 'amazon',  -- internal only; never shown store/customer-side
  vendor_order_ref  text,                            -- vendor order number (HQ-only)
  tracking          text,
  po_id             uuid,                            -- optional link to a commcalc.purchase_order (Phase 4)
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CONSTRAINT special_orders_product_fk
    FOREIGN KEY (org_id, product_id) REFERENCES pos.products (org_id, id)
);
CREATE INDEX IF NOT EXISTS ix_special_orders_org_status ON pos.special_orders (org_id, status);
CREATE INDEX IF NOT EXISTS ix_special_orders_org_store  ON pos.special_orders (org_id, store_code);

-- Special-order items are never stocked at a store (they ship in on demand), so they must be
-- INVENTORY-NEUTRAL regardless of the tenant's allow_negative_inventory setting — otherwise a tenant
-- that disables negative inventory would have every special-order checkout rejected for "no stock".
-- Re-create the sale-item inventory trigger with an early skip for is_special_order products. For every
-- OTHER product the behaviour is byte-identical to migration 725 (v_special is false → falls through).
CREATE OR REPLACE FUNCTION pos.apply_sale_item_inventory()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pos, pg_temp
AS $$
DECLARE
  v_store TEXT;
  v_allow BOOLEAN;
  v_on_hand NUMERIC;
  v_special BOOLEAN;
BEGIN
  -- mig 865: special-order lines never touch store inventory.
  SELECT p.is_special_order INTO v_special
    FROM pos.products p WHERE p.org_id = NEW.org_id AND p.id = NEW.product_id;
  IF COALESCE(v_special, false) THEN
    RETURN NEW;
  END IF;

  SELECT s.store_code INTO v_store FROM pos.sales s WHERE s.id = NEW.sale_id;

  IF NEW.serial_number IS NOT NULL AND btrim(NEW.serial_number) <> '' THEN
    UPDATE pos.inventory_serial i
       SET status = 'sold', sold_at = NOW(), sold_in_sale_id = NEW.sale_id, updated_at = NOW()
     WHERE i.org_id = NEW.org_id
       AND i.serial_number = NEW.serial_number
       AND i.status IN ('in_stock', 'in_transit');
  ELSIF v_store IS NOT NULL THEN
    v_allow := COALESCE((pos.pos_setting(NEW.org_id, v_store, 'allow_negative_inventory') #>> '{}')::boolean, true);
    IF NOT v_allow THEN
      SELECT st.qty_on_hand INTO v_on_hand FROM pos.inventory_standard st
       WHERE st.org_id = NEW.org_id AND st.product_id = NEW.product_id AND st.store_code = v_store;
      IF COALESCE(v_on_hand, 0) - COALESCE(NEW.qty, 0) < 0 THEN
        RAISE EXCEPTION 'Not enough stock for "%" (% on hand) — selling below zero is disabled in POS Settings.',
          COALESCE(NEW.description, 'item'), COALESCE(v_on_hand, 0);
      END IF;
    END IF;
    UPDATE pos.inventory_standard st
       SET qty_on_hand = st.qty_on_hand - COALESCE(NEW.qty, 0), updated_at = NOW()
     WHERE st.org_id = NEW.org_id
       AND st.product_id = NEW.product_id
       AND st.store_code = v_store;
  END IF;
  RETURN NEW;
END;
$$;

NOTIFY pgrst, 'reload schema';
SELECT 'Migration 865 complete — pos.special_orders + inventory-neutral trigger for special orders' AS status;
