-- 867_approvals_engine.sql — Unified Approvals Engine (owner directive 2026-08-19). See
-- docs/APPROVALS_AND_CHAT_PLAN.md.
--
-- ONE system every module routes its "needs approval / needs intimation" requests through, replacing
-- the ~20 bespoke approval flows. This migration adds the two core tables; modules become adapters that
-- write an approval_request on creation and flow their decision through the engine (approvals/engine.py).
--
-- Placed in the storeops schema (already PostgREST-exposed, service-role-only behind FastAPI — same
-- placement as the helpdesk module). Org-scoped per the migration-728 tenant-scoped-FK convention.
-- Additive + idempotent.
CREATE TABLE IF NOT EXISTS storeops.approval_requests (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id               uuid NOT NULL,
  request_no           bigint GENERATED BY DEFAULT AS IDENTITY,   -- human-friendly reference
  type                 text NOT NULL,                 -- e.g. 'timeclock_permission', 'shift_extension'
  source_table         text,                          -- the module's own record (adapter link)
  source_id            text,
  title                text NOT NULL,                 -- human summary line
  summary              text,
  payload              jsonb NOT NULL DEFAULT '{}'::jsonb,   -- type-specific render/decision data
  requested_by         text,                          -- employee_id of the requester
  requested_by_name    text,
  store_code           text,
  market               text,
  assignee_kind        text,                          -- 'dm'|'market'|'admin'|'role'|'user'
  assignee_employee_id text,
  assignee_email       text,
  status               text NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','approved','denied','cancelled','expired')),
  priority             text NOT NULL DEFAULT 'normal'
                       CHECK (priority IN ('normal','high','urgent')),
  decision             text,
  decided_by           text,
  decided_by_name      text,
  decided_at           timestamptz,
  decision_note        text,
  due_at               timestamptz,                   -- SLA
  escalated            boolean NOT NULL DEFAULT false,
  escalated_at         timestamptz,
  chat_message_id      uuid,                          -- link to the chat card (Part B), when posted
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id)
);
-- Idempotent creation: one live request per (type, source record). Partial so cancelled/expired rows
-- don't block a legitimate re-request for the same source later.
CREATE UNIQUE INDEX IF NOT EXISTS ux_approval_requests_source
  ON storeops.approval_requests (org_id, type, source_table, source_id)
  WHERE source_table IS NOT NULL AND source_id IS NOT NULL
        AND status IN ('pending','approved','denied');
CREATE INDEX IF NOT EXISTS ix_approval_requests_org_status ON storeops.approval_requests (org_id, status);
CREATE INDEX IF NOT EXISTS ix_approval_requests_org_store  ON storeops.approval_requests (org_id, store_code);
CREATE INDEX IF NOT EXISTS ix_approval_requests_org_type   ON storeops.approval_requests (org_id, type);

CREATE TABLE IF NOT EXISTS storeops.approval_events (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid NOT NULL,
  request_id   uuid NOT NULL,
  actor        text,                                  -- who acted (email/employee_id/'system')
  event_type   text NOT NULL,                         -- 'created'|'approved'|'denied'|'escalated'|...
  detail       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CONSTRAINT approval_events_request_fk
    FOREIGN KEY (org_id, request_id) REFERENCES storeops.approval_requests (org_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_approval_events_request ON storeops.approval_events (org_id, request_id, created_at);

NOTIFY pgrst, 'reload schema';
SELECT 'Migration 867 complete — storeops.approval_requests + approval_events (unified approvals engine)' AS status;
