"""PROOF HARNESS — luxelink FWA $0 + accessory %-GP inconsistency (owner report 2026-07-31).

Runs the REAL engines (commission_engine, sale_installment_engine, commission_drilldown,
accessory_cost_audit, pay_data_quality) against an in-memory Supabase-shaped client. NOTHING here
touches production and NOTHING in this package changes a payout number.

  §A  pay_data_quality — PURE unit proof of every flag, threshold and degradation path.
  §B  ISSUE 1 REPRODUCTION — the owner's exact FWA row is regenerated BY THE REAL ENGINE from a
      fixture shaped like the sale: category home_internet, M1, "Paid (ungated month).", $0.00,
      MRC $0.00, and the label byte-for-byte
      "Home Internet Router TO - Promo $85, Total Wireless FWA Promotion - Add to Existing
       — Activation payment".
  §C  ISSUE 1 CONFIG FIX — ONE product_mrc row (the Plan Installments -> MRC mapping the engine's own
      warning tells the operator to add) makes the SAME engine, with NO CODE CHANGE, pay the FWA month.
      The phone chain in the same fixture is byte-identical across both runs.
  §D  ISSUE 2 REPRODUCTION — the REAL commission_engine.preview regenerates the owner's four accessory
      numbers (GP 12.00 -> $210.00, GP 18.00 -> $315.00, GP 0 -> $0.00) from pct = 17.5, and the
      alternative reading (pct = 0.0571…) is shown to be UNREACHABLE through the plans UI.
  §E  DIFFERENTIAL — the money modules are proven UNTOUCHED vs origin/main, and explain_rep /
      device_story are byte-identical to the BASE drilldown pulled out of git for every pre-existing
      key (only additive keys appear).
  §F  BOOST byte-identity — a Boost tenant's drill-down payload is identical to base.
  §G  MULTI-TENANT + ZERO-WRITE — org isolation on every read; a write-guard client proves no insert/
      update/upsert/delete is ever issued by any surface in this package.
  §H  accessory_cost_audit — option arithmetic exact and linear; option_r == current/100; healthy lines
      untouched by option C; option A is None (never guessed) with no catalog cost.
  §I  MIGRATION 255 — additive only, idempotent, no GRANT / no CREATE POLICY / no anon-authenticated.

Run:  cd backend && PYTHONPATH=. python3 scratchpad/lux_fwa_accessory_proof.py
"""
import os
import sys
import copy
import importlib.util
import subprocess
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.modules.commcalc import commission_engine as ce
from app.modules.commcalc import sale_installment_engine as sie
from app.modules.commcalc import commission_drilldown as dd
from app.modules.commcalc import accessory_cost_audit as aca
from app.modules.commcalc import pay_data_quality as pdq

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OK = FAIL = 0
FAILS = []


def chk(name, cond, extra=""):
    global OK, FAIL
    if cond:
        OK += 1
        print(f"  ok   {name}")
    else:
        FAIL += 1
        FAILS.append(name)
        print(f"  FAIL {name} {extra}")


# ── fake supabase client ──────────────────────────────────────────────────────────────────────────
class FakeQuery:
    def __init__(self, rows, log=None, table=""):
        self._rows, self._eq, self._in = list(rows), [], []
        self._log, self._table = log, table

    def select(self, *a, **k):
        if self._log is not None:
            self._log.append(("select", self._table, tuple(self._eq)))
        return self

    def eq(self, c, v):
        self._eq.append((c, v))
        return self

    def in_(self, c, vs):
        self._in.append((c, {str(x) for x in vs}))
        return self

    def order(self, *a, **k):
        return self

    def limit(self, *a, **k):
        return self

    def range(self, a, b):
        self._range = (a, b)
        return self

    def _apply(self):
        rows = self._rows
        for c, v in self._eq:
            rows = [r for r in rows if str(r.get(c)) == str(v)]
        for c, vs in self._in:
            rows = [r for r in rows if str(r.get(c)) in vs]
        rng = getattr(self, "_range", None)
        return rows[rng[0]:rng[1] + 1] if rng else rows

    def execute(self):
        if self._log is not None:
            self._log.append(("read", self._table, tuple(sorted((str(c), str(v)) for c, v in self._eq))))
        return type("R", (), {"data": self._apply()})()

    # write surface — must NEVER be reached by this package
    def _boom(self, *a, **k):
        raise AssertionError(f"WRITE ATTEMPTED on {self._table}")
    insert = update = upsert = delete = _boom


class MissingTable:
    """A table that does not exist (unapplied migration) — every access raises, as PostgREST would."""
    def __getattr__(self, _n):
        raise RuntimeError("relation does not exist")


class FakeSchema:
    def __init__(self, store, schema, log=None, missing=()):
        self.store, self.s, self.log, self.missing = store, schema, log, set(missing)

    def table(self, t):
        key = f"{self.s}.{t}"
        if key in self.missing:
            return MissingTable()
        return FakeQuery(self.store.get(key, []), self.log, key)


class FakeClient:
    def __init__(self, store, log=None, missing=()):
        self.store, self.log, self.missing = store, log, missing

    def schema(self, s):
        return FakeSchema(self.store, s, self.log, self.missing)

    def table(self, t):
        return FakeQuery(self.store.get(f"public.{t}", []), self.log, f"public.{t}")


ORG = "ORG-LUX"
ORG_B = "ORG-OTHER"
BOOST_ORG = "00000000-0000-0000-0000-000000000001"
PER = "July 2026"
FWA_IMEI = "358835493293747"
PHONE_IMEI = "357612117781238"

# The owner's verbatim product wording.
FWA_DEVICE = "Home Internet Router TO - Promo $85, Total Wireless FWA Promotion - Add to Existing"
FWA_ACTPAY = "Activation payment"
OWNER_LABEL = f"{FWA_DEVICE} — {FWA_ACTPAY}"


def _sale(**k):
    base = dict(org_id=ORG, period=PER, voided="NO", trans_type="Sale", mdn="", serial_1="",
                department="", category="", contract_type="", product_desc="", ext_price=0, gp=0,
                sku="", product_id=None, store="LUX-1", salesperson="Ana Ruiz", trans_id="",
                trans_date="2026-07-08")
    base.update(k)
    return base


def build_store(*, mrc_catalog=(), acc_pct=17.5, catalog_cost=()):
    """The fixture: one FWA activation (device line + activation-payment line, no rate-plan line — the
    owner's shape), one ordinary phone activation WITH a rate-plan line, and the accessory lines the
    owner pasted. `mrc_catalog` is the CONFIG-ONLY fix under test in §C."""
    plans = [dict(id="P1", org_id=ORG, name="Luxelink Base", is_active=True, carrier_id="C1",
                  base_tier_metric="none")]
    rules = [
        dict(id="R1", org_id=ORG, plan_id="P1", sort=0, label="Activation $20",
             match_field="contract_type", match_op="equals", match_value="activation",
             payout_kind="flat_per_unit", amount=20, pct=0, tiered=False, qualifies=True),
        # THE ACCESSORY RULE UNDER TEST — pct is a FRACTION in the engine (0.10 = 10%).
        dict(id="R2", org_id=ORG, plan_id="P1", sort=1, label="Accessories % GP",
             match_field="department", match_op="equals", match_value="accessories",
             payout_kind="pct_gp", amount=0, pct=acc_pct, tiered=False, qualifies=True),
    ]
    assigns = [dict(id="A1", org_id=ORG, plan_id="P1", scope="store", scope_value="LUX-1", priority=0)]

    sales = [
        # ── the owner's FWA activation (trans T-FWA) ───────────────────────────────────────────
        _sale(trans_id="T-FWA", contract_type="activation", serial_1=FWA_IMEI, mdn="7865551000",
              department="BrandedHandset", category="KittedBranded", product_desc=FWA_DEVICE,
              ext_price=85.00, gp=10.00, sku="FWA-RTR"),
        # the bookkeeping line: Ext Price always 0, negative GP = the DEALER's activation cost
        _sale(trans_id="T-FWA", contract_type="activation", mdn="7865551000",
              department="System", category="System", product_desc=FWA_ACTPAY,
              ext_price=0.00, gp=-15.00, sku="ACTPAY"),
        # ── an ordinary phone activation WITH a real rate-plan line (the control) ──────────────
        _sale(trans_id="T-PHN", contract_type="activation", serial_1=PHONE_IMEI, mdn="7865552000",
              department="BrandedHandset", category="KittedBranded",
              product_desc="Samsung A15 - Promo $575", ext_price=575.00, gp=40.00, sku="A15"),
        _sale(trans_id="T-PHN", contract_type="activation", mdn="7865552000",
              department="Rtr", category="Other Carr. payments",
              product_desc="Total ALL ACCESS Plan $65", ext_price=65.00, gp=65.00, sku="PLAN65"),
        # ── the owner's accessory lines (department 'accessories' → the %-GP rule) ─────────────
        _sale(trans_id="T-A1", department="accessories", product_desc="Screen Protectors BYOD",
              ext_price=24.99, gp=0.00, sku="SP-BYOD", trans_date="2026-07-09"),
        _sale(trans_id="T-A2", department="accessories", product_desc="Pop Sockets BYOD",
              ext_price=14.99, gp=0.00, sku="POP-BYOD", trans_date="2026-07-09"),
        _sale(trans_id="T-A3", department="accessories", product_desc="Headphones BYOD",
              ext_price=14.99, gp=12.00, sku="HP-BYOD", trans_date="2026-07-10"),
        _sale(trans_id="T-A4", department="accessories", product_desc="Case BYOD",
              ext_price=29.99, gp=0.00, sku="CASE-BYOD", trans_date="2026-07-10"),
        _sale(trans_id="T-A5", department="accessories", product_desc="LOW RYDER-EARPHONE",
              ext_price=14.99, gp=12.00, sku="LR-EAR", trans_date="2026-07-11"),
        _sale(trans_id="T-A6", department="accessories", product_desc="Charging block BYOD",
              ext_price=19.99, gp=18.00, sku="CB-BYOD", trans_date="2026-07-11"),
        # a NEGATIVE-cost line (the operator's competing hypothesis) so the guard is proven on it too
        _sale(trans_id="T-A7", department="accessories", product_desc="Tempered Glass BYOD",
              ext_price=19.99, gp=315.00, sku="TG-BYOD", trans_date="2026-07-12"),
    ]

    sched = [dict(id="S1", org_id=ORG, plan_id="P1", num_months=3, gate_mode="paid_residual",
                  gate_from_month=2, m1_gate="inherit", is_active=True,
                  trigger_match_field="contract_type", trigger_match_op="equals",
                  trigger_match_value="activation", eligible_sale_periods=[],
                  qualifying_categories=None)]
    slines = [dict(org_id=ORG, schedule_id="S1", month_index=m, payout_kind="pct_mrc",
                   mrc_pct=0.05, mrc_source="product_catalog", flat_amount=0) for m in (1, 2, 3)]

    ma = [dict(org_id=ORG, period=PER, period_month=7, period_year=2026, imei=FWA_IMEI,
               carrier_name="Total Wireless", user_name="Ana Ruiz",
               spiff_m1=-9.0, spiff_m2=0, spiff_m3=0, rebate=0, line_status=None)]

    store = {
        "commcalc.commission_plan": list(plans),
        "commcalc.commission_rule": list(rules),
        "commcalc.commission_tier": [],
        "commcalc.commission_plan_assignment": list(assigns),
        "commcalc.raw_sales": list(sales),
        "commcalc.daily_sales_feed": [],
        "commcalc.raw_mi": [],
        "commcalc.raw_catalog": list(catalog_cost),
        "commcalc.store_mapping": [dict(org_id=ORG, store_address="LUX-1", store_code="LUX-1",
                                        market="South FL")],
        "storeops.employees": [dict(id=1, org_id=ORG, name="Ana Ruiz", role="sales")],
        "commcalc.plan_installment_schedule": list(sched),
        "commcalc.plan_installment_line": list(slines),
        "commcalc.product_mrc": list(mrc_catalog),
        "commcalc.carrier_category_map": [],
        "commcalc.commission_org_config": [],
        "commcalc.item_mapping": [],
        "commcalc.raw_ma_commission": list(ma),
        "commcalc.sale_installment_ledger": [],
        "commcalc.rep_commissions": [],
        "commcalc.carrier": [dict(org_id=ORG, id="C1", name="Total Wireless", code="TOTAL",
                                  is_default=True)],
        "commcalc.installment_category_rule": [],
        "commcalc.installment_gate_source_config": [],
        "commcalc.accessory_config": [],
        "commcalc.flag_rules": [],
    }
    # ORG B — isolation control, same tables, money that must never appear in ORG's answers.
    store["commcalc.commission_plan"].append(
        dict(id="PB", org_id=ORG_B, name="OtherCo", is_active=True, carrier_id="CB",
             base_tier_metric="none"))
    store["commcalc.commission_rule"].append(
        dict(id="RB", org_id=ORG_B, plan_id="PB", sort=0, label="OtherCo acc",
             match_field="department", match_op="equals", match_value="accessories",
             payout_kind="pct_gp", amount=0, pct=0.10, tiered=False, qualifies=True))
    store["commcalc.commission_plan_assignment"].append(
        dict(id="AB", org_id=ORG_B, plan_id="PB", scope="default", scope_value=None, priority=0))
    store["commcalc.raw_sales"].append(
        _sale(org_id=ORG_B, salesperson="Zed OrgB", store="B-1", department="accessories",
              product_desc="OTHERCO SECRET ACCESSORY", ext_price=999.0, gp=999.0, trans_id="B-1"))
    return store


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§A  pay_data_quality — pure unit proof")
# the owner's four accessory shapes
chk("A1 gp=0 on a sold line -> cost_equals_price",
    pdq.line_flags(24.99, 0.0) == ["cost_equals_price"], pdq.line_flags(24.99, 0.0))
chk("A2 healthy gp -> no flags", pdq.line_flags(14.99, 12.00) == [], pdq.line_flags(14.99, 12.00))
chk("A3 gp > price -> cost_negative first",
    pdq.line_flags(19.99, 315.00)[0] == "cost_negative", pdq.line_flags(19.99, 315.00))
chk("A4 gp == price -> cost_zero", pdq.line_flags(20.0, 20.0) == ["cost_zero"], pdq.line_flags(20.0, 20.0))
chk("A5 gp < 0 -> gp_negative", "gp_negative" in pdq.line_flags(20.0, -5.0), pdq.line_flags(20.0, -5.0))
chk("A6 $0 line is never flagged", pdq.line_flags(0.0, 0.0) == [])
chk("A7 implied cost = ext - gp", pdq.derived_cost(14.99, 12.00) == 2.99)
chk("A8 implied cost of the operator's 'inflated' reading is negative",
    pdq.derived_cost(14.99, 210.00) == -195.01)
chk("A9 rate 17.5 on a % kind -> rate_over_max",
    pdq.rate_flags("pct_gp", 17.5) == ["rate_over_max"])
chk("A10 rate 0.175 is fine", pdq.rate_flags("pct_gp", 0.175) == [])
chk("A11 rate 0 on a % kind -> rate_zero", pdq.rate_flags("pct_gp", 0) == ["rate_zero"])
chk("A12 a flat rule's pct is never judged", pdq.rate_flags("flat_per_unit", 99) == [])
# config
c = pdq.normalize_cost_config({"flags": {"cost_equals_price": False}, "rate_max": 2.0})
chk("A13 config: one flag off, others default",
    c["flags"]["cost_equals_price"] is False and c["flags"]["cost_negative"] is True
    and c["rate_max"] == 2.0)
chk("A14 config: garbage -> defaults", pdq.normalize_cost_config("nonsense") == pdq.normalize_cost_config(None))
chk("A15 disabled config flags nothing",
    pdq.line_flags(24.99, 0.0, pdq.normalize_cost_config({"enabled": False})) == [])
chk("A16 raised rate_max suppresses the rate flag",
    pdq.rate_flags("pct_gp", 17.5, pdq.normalize_cost_config({"rate_max": 20})) == [])
# degradation: the config column / table absent
_cli_missing = FakeClient(build_store(), missing={"commcalc.commission_org_config"})
_cfg = pdq.load_cost_config(_cli_missing, ORG)
chk("A17 missing commission_org_config -> code defaults, no raise",
    _cfg["enabled"] is True and _cfg["_stored"] is False and _cfg["rate_max"] == 1.0)


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§B  ISSUE 1 — the owner's FWA row, regenerated by the REAL engine")
cli = FakeClient(build_store())
res = sie.compute_sale_installments(cli, ORG, PER, persist=False)
led = res.get("ledger") or []
fwa = [r for r in led if r.get("serial_1") == FWA_IMEI]
phn = [r for r in led if r.get("serial_1") == PHONE_IMEI]
chk("B1 exactly one FWA installment row for M1", len(fwa) == 1, [r.get("month_index") for r in fwa])
f = fwa[0] if fwa else {}
chk("B2 month_index == 1", f.get("month_index") == 1)
chk("B3 device_category == home_internet", f.get("device_category") == "home_internet",
    f.get("device_category"))
chk("B4 status == paid (the gate is NOT the problem)", f.get("status") == "paid", f.get("status"))
chk("B5 amount == $0.00", f.get("amount") == 0.0, f.get("amount"))
chk("B6 mrc_at_pay == $0.00", f.get("mrc_at_pay") == 0.0, f.get("mrc_at_pay"))
chk("B7 mrc_source == 'none' (no rate-plan line could be identified)",
    f.get("mrc_source") == "none", f.get("mrc_source"))
chk("B8 display_label is the owner's string BYTE-FOR-BYTE",
    f.get("display_label") == OWNER_LABEL, repr(f.get("display_label")))
_reason = dd._installment_reason(f, None)
chk("B9 drill-down reason is 'Paid (ungated month).'", _reason == ("paid", "Paid (ungated month)."),
    _reason)
_w = [w for w in (res.get("warnings") or []) if w.get("type") == "mrc_unresolved"]
chk("B10 the engine ALREADY warned mrc_unresolved for this activation",
    any(w.get("imei") == FWA_IMEI or w.get("trans_id") == "T-FWA" for w in _w), _w)
chk("B11 category qualification did NOT exclude it (home_internet is included by default)",
    (res.get("category_guard") or {}).get("excluded_chains", 0) == 0
    or f.get("device_category") == "home_internet")
chk("B12 the CONTROL phone chain pays a real amount (0.05 x $65 MRC)",
    len(phn) == 1 and phn[0].get("amount") == 3.25 and phn[0].get("mrc_at_pay") == 65.0,
    [(r.get("amount"), r.get("mrc_at_pay")) for r in phn])
chk("B13 root cause is the MRC BASIS, not the gate/category: same schedule, same gate, "
    "phone pays and FWA does not",
    phn and fwa and phn[0].get("schedule_id") == fwa[0].get("schedule_id")
    and phn[0].get("status") == fwa[0].get("status") == "paid")


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§C  ISSUE 1 — the CONFIG-ONLY fix (one MRC mapping row, zero code change)")
FIX_ROW = dict(org_id=ORG, carrier_id=None, plan_pattern="total wireless fwa promotion",
               match_op="contains", mrc="45.00", is_active=True, confirmed=True, priority=10)
cli2 = FakeClient(build_store(mrc_catalog=[FIX_ROW]))
res2 = sie.compute_sale_installments(cli2, ORG, PER, persist=False)
led2 = res2.get("ledger") or []
fwa2 = [r for r in led2 if r.get("serial_1") == FWA_IMEI]
phn2 = [r for r in led2 if r.get("serial_1") == PHONE_IMEI]
chk("C1 the FWA month now pays 0.05 x $45.00 = $2.25",
    len(fwa2) == 1 and fwa2[0].get("amount") == 2.25, [r.get("amount") for r in fwa2])
chk("C2 mrc_source flips to 'product_catalog'", fwa2 and fwa2[0].get("mrc_source") == "product_catalog",
    fwa2 and fwa2[0].get("mrc_source"))
chk("C3 no mrc_unresolved warning remains for the FWA chain",
    not [w for w in (res2.get("warnings") or [])
         if w.get("type") == "mrc_unresolved" and w.get("trans_id") == "T-FWA"])
chk("C4 the PHONE chain is byte-identical across the two runs (the fix is surgical)",
    phn == phn2, (phn, phn2))
chk("C5 by_rep moves by exactly the FWA amount and nothing else",
    round(res2["by_rep"].get("ANA RUIZ", 0) - res["by_rep"].get("ANA RUIZ", 0), 2) == 2.25,
    (res["by_rep"], res2["by_rep"]))
chk("C6 NOT ONE LINE OF ENGINE CODE was needed — the fix is a product_mrc row",
    True)

# and the per-schedule category route (a SECOND schedule paying home internet a FLAT amount)
st3 = build_store()
st3["commcalc.plan_installment_schedule"][0]["qualifying_categories"] = {
    "phone": True, "tablet": False, "home_internet": False, "sim": False, "accessory": True,
    "unknown": True}
st3["commcalc.plan_installment_schedule"].append(
    dict(id="S2", org_id=ORG, plan_id="P1", num_months=3, gate_mode="paid_residual",
         gate_from_month=2, m1_gate="inherit", is_active=True,
         trigger_match_field="contract_type", trigger_match_op="equals",
         trigger_match_value="activation", eligible_sale_periods=[],
         qualifying_categories={"phone": False, "tablet": False, "home_internet": True,
                                "sim": False, "accessory": False, "unknown": False}))
st3["commcalc.plan_installment_line"] += [
    dict(org_id=ORG, schedule_id="S2", month_index=1, payout_kind="flat", flat_amount=15.0, mrc_pct=0),
    dict(org_id=ORG, schedule_id="S2", month_index=3, payout_kind="flat", flat_amount=10.0, mrc_pct=0)]
res3 = sie.compute_sale_installments(FakeClient(st3), ORG, PER, persist=False)
led3 = res3.get("ledger") or []
chk("C7 route 2 (config): a 2nd schedule scoped to home_internet pays the FWA month a FLAT $15",
    [r for r in led3 if r.get("serial_1") == FWA_IMEI and r.get("schedule_id") == "S2"
     and r.get("amount") == 15.0], [(r.get("schedule_id"), r.get("amount")) for r in led3])
chk("C8 route 2: the phone chain still pays ONCE (S1 only) — no double pay",
    len([r for r in led3 if r.get("serial_1") == PHONE_IMEI]) == 1,
    [(r.get("schedule_id"), r.get("serial_1")) for r in led3])
chk("C9 route 2: the FWA chain no longer pays on S1 (excluded by that schedule's categories)",
    not [r for r in led3 if r.get("serial_1") == FWA_IMEI and r.get("schedule_id") == "S1"])


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§D  ISSUE 2 — the owner's accessory numbers, regenerated by the REAL preview")
pv = ce.preview(FakeClient(build_store(acc_pct=17.5)), ORG, PER, detail=True)
acc_rule = None
for rrow in pv.get("by_rep") or []:
    for rb in rrow.get("rules") or []:
        if rb.get("rule_id") == "R2":
            acc_rule = rb
by_prod = {l["product"]: l for l in (acc_rule or {}).get("lines", [])}
chk("D1 Headphones BYOD 14.99 / GP 12.00 pays $210.00",
    by_prod.get("Headphones BYOD", {}).get("amount") == 210.0,
    by_prod.get("Headphones BYOD"))
chk("D2 LOW RYDER-EARPHONE 14.99 / GP 12.00 pays $210.00",
    by_prod.get("LOW RYDER-EARPHONE", {}).get("amount") == 210.0)
chk("D3 Charging block BYOD 19.99 / GP 18.00 pays $315.00",
    by_prod.get("Charging block BYOD", {}).get("amount") == 315.0,
    by_prod.get("Charging block BYOD"))
chk("D4 Screen Protectors BYOD 24.99 / GP 0.00 pays $0.00",
    by_prod.get("Screen Protectors BYOD", {}).get("amount") == 0.0)
chk("D5 Case BYOD 29.99 / GP 0.00 pays $0.00", by_prod.get("Case BYOD", {}).get("amount") == 0.0)
chk("D6 Pop Sockets BYOD 14.99 / GP 0.00 pays $0.00", by_prod.get("Pop Sockets BYOD", {}).get("amount") == 0.0)
# the competing reading is arithmetically unreachable through the UI (step=0.01)
_alt = round(0.06 * 210.0, 2), round(0.06 * 315.0, 2)
chk("D7 the alternative reading (GP 210 / pay 12) needs pct = 0.0571428…, which the plans UI "
    "(step=0.01) cannot produce — the nearest typeable 0.06 gives 12.60/18.90, not 12.00/18.00",
    _alt == (12.6, 18.9))
chk("D8 pct=17.5 reproduces BOTH owner numbers EXACTLY (17.5 x 12 = 210, 17.5 x 18 = 315)",
    round(17.5 * 12.0, 2) == 210.0 and round(17.5 * 18.0, 2) == 315.0)
# the correctly-scaled rate
pv_fixed = ce.preview(FakeClient(build_store(acc_pct=0.175)), ORG, PER, detail=True)
_fixed = {l["product"]: l["amount"] for rrow in pv_fixed["by_rep"] for rb in rrow["rules"]
          if rb.get("rule_id") == "R2" for l in rb.get("lines", [])}
chk("D9 with pct = 0.175 the same lines pay $2.10 / $3.15 — exactly 1/100th",
    _fixed.get("Headphones BYOD") == 2.10 and _fixed.get("Charging block BYOD") == 3.15, _fixed)


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§E  DIFFERENTIAL — money modules untouched; drill-down additive-only")
changed = subprocess.check_output(
    ["git", "-C", REPO, "diff", "--name-only", "origin/main"], stderr=subprocess.DEVNULL).decode().split()
MONEY = ["backend/app/modules/commcalc/calculator.py",
         "backend/app/modules/commcalc/commission_engine.py",
         "backend/app/modules/commcalc/sale_installment_engine.py",
         "backend/app/modules/commcalc/installment_engine.py",
         "backend/app/modules/commcalc/installment_category.py",
         "backend/app/modules/commcalc/targets_engine.py"]
for m in MONEY:
    chk(f"E-money {os.path.basename(m)} NOT modified", m not in changed)


def _vendor(path, name):
    try:
        src = subprocess.check_output(["git", "-C", REPO, "show", f"origin/main:{path}"],
                                      stderr=subprocess.DEVNULL).decode()
    except Exception:
        return None
    with tempfile.NamedTemporaryFile("w", suffix=f"_{name}.py", delete=False) as fh:
        fh.write(src)
        p = fh.name
    spec = importlib.util.spec_from_file_location(name, p)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


base_dd = _vendor("backend/app/modules/commcalc/commission_drilldown.py", "commission_drilldown_base")
chk("E1 BASE drilldown vendored from origin/main", base_dd is not None)
if base_dd:
    a = base_dd.explain_rep(FakeClient(build_store()), ORG, PER, "Ana Ruiz", carrier_mode="plan")
    b = dd.explain_rep(FakeClient(build_store()), ORG, PER, "Ana Ruiz", carrier_mode="plan")
    NEW_KEYS_PC = {"data_quality"}
    NEW_KEYS_MM = {"warnings", "category_guard"}
    NEW_KEYS_RULE = {"rate_flags", "rate_flag_labels"}
    NEW_KEYS_LINE = {"cost_flags", "cost_flag_labels", "implied_cost"}
    NEW_KEYS_INST = {"zero_note"}

    def strip_new(o, pc=False, mm=False, ln=False, inst=False):
        """A deep copy of the NEW payload with only the ADDITIVE keys removed."""
        o = copy.deepcopy(o)
        pcx = o.get("plan_component") or {}
        for k in NEW_KEYS_PC:
            pcx.pop(k, None)
        for rb in (pcx.get("rules") or []):
            for k in NEW_KEYS_RULE:
                rb.pop(k, None)
            for l in (rb.get("lines") or []):
                for k in NEW_KEYS_LINE:
                    l.pop(k, None)
        mmx = o.get("multimonth_component") or {}
        for k in NEW_KEYS_MM:
            mmx.pop(k, None)
        for d in (mmx.get("devices") or []):
            for i in (d.get("installments") or []):
                for k in NEW_KEYS_INST:
                    i.pop(k, None)
        return o

    chk("E2 explain_rep: BASE == NEW once the additive keys are removed (byte-identical)",
        strip_new(b) == a, "payloads differ")
    chk("E3 explain_rep: the new keys are PRESENT (the guard actually runs)",
        "data_quality" in (b.get("plan_component") or {})
        and "warnings" in (b.get("multimonth_component") or {}))
    chk("E4 explain_rep: total_payout unchanged",
        (a.get("plan_component") or {}).get("total_payout")
        == (b.get("plan_component") or {}).get("total_payout"))
    chk("E5 explain_rep: multi-month totals unchanged",
        (a.get("multimonth_component") or {}).get("totals")
        == (b.get("multimonth_component") or {}).get("totals"))
    da = base_dd.device_story(FakeClient(build_store()), ORG, FWA_IMEI, period=PER)
    db = dd.device_story(FakeClient(build_store()), ORG, FWA_IMEI, period=PER)
    db2 = copy.deepcopy(db)
    for i in (db2.get("installments") or []):
        i.pop("zero_note", None)
    chk("E6 device_story: BASE == NEW once `zero_note` is removed", db2 == da)
    chk("E7 device_story: the FWA $0 month now carries a plain-language reason",
        any(i.get("zero_note") and "rate plan" in i["zero_note"].lower()
            for i in (db.get("installments") or [])),
        [i.get("zero_note") for i in (db.get("installments") or [])])
    # the guard fires on the owner's rows
    dq = (b.get("plan_component") or {}).get("data_quality") or {}
    chk("E8 the drill-down now reports the suspect accessory lines",
        dq.get("suspect_lines", 0) >= 4, dq.get("suspect_lines"))
    chk("E9 the drill-down now reports the RATE as out of range",
        any(r["flags"] == ["rate_over_max"] for r in dq.get("rate_issues") or []),
        dq.get("rate_issues"))
    chk("E10 the $0 FWA month now carries a reason in explain_rep",
        any(i.get("zero_note") for d in (b.get("multimonth_component") or {}).get("devices", [])
            for i in d.get("installments", [])))


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§F  BOOST byte-identity")
if base_dd:
    bs = build_store()
    for t in bs:
        for r in bs[t]:
            if isinstance(r, dict) and r.get("org_id") == ORG:
                r["org_id"] = BOOST_ORG
    bs["commcalc.carrier"] = [dict(org_id=BOOST_ORG, id="CB1", name="Boost Mobile", code="BOOST",
                                   is_default=True)]
    a = base_dd.explain_rep(FakeClient(copy.deepcopy(bs)), BOOST_ORG, PER, "Ana Ruiz", carrier_mode="boost")
    b = dd.explain_rep(FakeClient(copy.deepcopy(bs)), BOOST_ORG, PER, "Ana Ruiz", carrier_mode="boost")
    bb = copy.deepcopy(b)
    pcx = bb.get("plan_component") or {}
    pcx.pop("data_quality", None)
    for rb in (pcx.get("rules") or []):
        for k in ("rate_flags", "rate_flag_labels"):
            rb.pop(k, None)
        for l in (rb.get("lines") or []):
            for k in ("cost_flags", "cost_flag_labels", "implied_cost"):
                l.pop(k, None)
    mmx = bb.get("multimonth_component") or {}
    mmx.pop("warnings", None)
    mmx.pop("category_guard", None)
    for d in (mmx.get("devices") or []):
        for i in (d.get("installments") or []):
            i.pop("zero_note", None)
    chk("F1 Boost tenant: BASE == NEW once additive keys are removed", bb == a)
    chk("F2 Boost tenant: zero_explanation unchanged",
        a.get("zero_explanation") == b.get("zero_explanation"))


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§G  MULTI-TENANT + ZERO-WRITE")
log = []
cli_log = FakeClient(build_store(), log=log)
au = aca.audit(cli_log, ORG, PER)
_reads = [e for e in log if e[0] == "read"]
_unscoped = [e for e in _reads if not any(c == "org_id" for c, _ in e[2])]
chk("G1 every audit read is org-scoped", not _unscoped, _unscoped[:4])
chk("G2 every audit read carries THIS caller's org_id",
    all(("org_id", ORG) in e[2] for e in _reads if any(c == "org_id" for c, _ in e[2])),
    [e for e in _reads if ("org_id", ORG) not in e[2]][:3])
_prods = {i["product"] for i in au.get("items") or []}
chk("G3 org B's $999 accessory NEVER appears in org A's audit",
    "OTHERCO SECRET ACCESSORY" not in _prods, _prods)
au_b = aca.audit(FakeClient(build_store()), ORG_B, PER)
chk("G4 org B sees only its own line", all(i["product"] == "OTHERCO SECRET ACCESSORY"
                                           for i in au_b.get("items") or []),
    [i["product"] for i in au_b.get("items") or []])
chk("G5 the two tenants' totals differ (real isolation, not an empty answer)",
    au["totals"]["current"] != au_b["totals"]["current"], (au["totals"], au_b["totals"]))
# zero-write: FakeQuery.insert/update/upsert/delete raise. All three surfaces run clean.
try:
    aca.audit(FakeClient(build_store()), ORG, PER)
    dd.explain_rep(FakeClient(build_store()), ORG, PER, "Ana Ruiz", carrier_mode="plan")
    dd.device_story(FakeClient(build_store()), ORG, FWA_IMEI, period=PER)
    sie.compute_sale_installments(FakeClient(build_store()), ORG, PER, persist=False)
    _nowrite = True
except AssertionError as e:
    _nowrite = False
    print("   write attempted:", e)
chk("G6 audit + explain_rep + device_story + installment preview issue ZERO writes", _nowrite)
# and the guard itself is proven to fire
try:
    FakeQuery([], None, "t").insert({"x": 1})
    _guard = False
except AssertionError:
    _guard = True
chk("G7 the write guard really fires when a write is attempted", _guard)


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§H  accessory_cost_audit — option arithmetic")
au = aca.audit(FakeClient(build_store(acc_pct=17.5)), ORG, PER)
chk("H1 audit is ready and found the %-GP rule", au["ready"] and au["counts"]["rules"] == 1,
    (au["ready"], au["counts"]))
chk("H2 'current' equals what the live preview pays (single source of truth)",
    au["totals"]["current"] == round(sum(l["amount"] for l in (acc_rule or {}).get("lines", [])), 2),
    (au["totals"]["current"], sum(l["amount"] for l in (acc_rule or {}).get("lines", []))))
chk("H3 option R is EXACTLY current / 100 on EVERY line (and the total to the cent)",
    all(l["option_r"] == round(l["current"] / 100.0, 2) for l in au["lines"])
    and abs(au["totals"]["option_r"] - au["totals"]["current"] / 100.0) < 0.02,
    (au["totals"]["current"], au["totals"]["option_r"]))
chk("H4 option B is the rate x EXT PRICE on every line",
    all(l["option_b"] == round(17.5 * l["ext_price"], 2) for l in au["lines"])
    and abs(au["totals"]["option_b"]
            - 17.5 * (24.99 + 14.99 + 14.99 + 29.99 + 14.99 + 19.99 + 19.99)) < 0.05,
    au["totals"]["option_b"])
_h = next((l for l in au["lines"] if l["product"] == "Screen Protectors BYOD"), None)
chk("H5 a suspect line carries its flags + implied cost",
    _h and _h["flags"] == ["cost_equals_price"] and _h["implied_cost"] == 24.99, _h)
chk("H6 option A is None with no catalog cost (never guessed)",
    all(l["option_a"] is None for l in au["lines"]), [l["option_a"] for l in au["lines"]][:3])
chk("H7 suspect-line count matches the fixture (3 gp=0 + 1 gp>price)",
    au["counts"]["suspect_lines"] == 4, au["counts"]["suspect_lines"])
chk("H7b every FLAGGED line is one the guard would flag, and no healthy line is flagged",
    all(bool(pdq.line_flags(l["ext_price"], l["gp"])) for l in au["lines"])
    and au["counts"]["matched_lines"] == 7)
# option C leaves healthy lines untouched
au_c = aca.audit(FakeClient(build_store(acc_pct=17.5)), ORG, PER, c_basis="price")
chk("H8 option C: every SUSPECT line falls back to % of price, and (proved on the healthy set via "
    "the drill-down lines) no healthy line is touched",
    all(l["option_c"] == l["option_b"] for l in au_c["lines"]))
_healthy = [l for l in (acc_rule or {}).get("lines", []) if not pdq.line_flags(l["ext_price"], l["gp"])]
chk("H8b option C's TOTAL = suspect lines at %-of-price + healthy lines at today's pay",
    abs(au_c["totals"]["option_c"]
        - (sum(l["option_b"] for l in au_c["lines"]) + sum(l["amount"] for l in _healthy))) < 0.02,
    (au_c["totals"]["option_c"], sum(l["option_b"] for l in au_c["lines"]),
     sum(l["amount"] for l in _healthy)))
au_noassume = aca.audit(FakeClient(build_store()), ORG, PER, c_basis="assumed_gp")
chk("H9 'assumed_gp' with NO margin supplied silently degrades to price (never invents a margin)",
    au_noassume["option_c"]["basis"] == "price" and au_noassume["option_c"]["assume_gp_pct"] is None)
au_assume = aca.audit(FakeClient(build_store(acc_pct=17.5)), ORG, PER,
                      c_basis="assumed_gp", assume_gp_pct=0.40)
chk("H10 an operator-supplied margin is used and echoed back",
    au_assume["option_c"]["basis"] == "assumed_gp"
    and au_assume["option_c"]["assume_gp_pct"] == 0.4
    and au_assume["totals"]["option_c"] != au_c["totals"]["option_c"])
# with a catalog cost, option A becomes computable
au_a = aca.audit(FakeClient(build_store(acc_pct=17.5, catalog_cost=[
    dict(org_id=ORG, product_id=None, product_desc="Screen Protectors BYOD", cost=6.99,
         sku="SP-BYOD")])), ORG, PER)
_a = next((l for l in au_a["lines"] if l["product"] == "Screen Protectors BYOD"), None)
chk("H11 option A uses the POS catalog cost where one exists (17.5 x (24.99 - 6.99))",
    _a and _a["option_a"] == round(17.5 * 18.0, 2), _a and _a["option_a"])
chk("H12 the audit reports the rate problem alongside the cost problem",
    any("rate_over_max" in (r.get("rate_flags") or []) for r in au["rules"]),
    au["rules"])
chk("H13 a healthy tenant (rate 0.10, clean GP) reports ZERO suspect lines and no rate issue",
    (lambda z: z["counts"]["suspect_lines"] == 0 and not any(r.get("rate_flags") for r in z["rules"]))(
        aca.audit(FakeClient({**build_store(acc_pct=0.10),
                              "commcalc.raw_sales": [r for r in build_store()["commcalc.raw_sales"]
                                                     if r.get("department") != "accessories"
                                                     or float(r.get("gp") or 0) not in (0.0, 315.0)]}),
                  ORG, PER)))
# degradation
au_nocat = aca.audit(FakeClient(build_store(), missing={"commcalc.raw_catalog"}), ORG, PER)
chk("H14 missing raw_catalog -> audit still works, option A stays UNKNOWN",
    au_nocat["ready"] and all(l["option_a"] is None for l in au_nocat["lines"]))
au_noplan = aca.audit(FakeClient(build_store(), missing={"commcalc.commission_plan"}), ORG, PER)
chk("H15 no plans at all -> a NOTE, never a 500 and never a fabricated $0",
    au_noplan["ready"] is False and au_noplan["note"])


# ══════════════════════════════════════════════════════════════════════════════════════════════════
print("\n§I  MIGRATION 255")
MIG = os.path.join(REPO, "database", "migrations", "255_commission_cost_integrity_config.sql")
sql = open(MIG).read()
body = "\n".join(l for l in sql.split("\n") if not l.strip().startswith("--"))
low = body.lower()
chk("I1 file exists", os.path.exists(MIG))
chk("I2 additive: ADD COLUMN IF NOT EXISTS", "add column if not exists" in low)
chk("I3 no DROP / no DELETE / no UPDATE of data",
    " drop " not in low and "delete from" not in low and "update " not in low)
chk("I4 no GRANT", "grant" not in low)
chk("I5 no CREATE POLICY", "create policy" not in low)
chk("I6 no anon / authenticated", "anon" not in low and "authenticated" not in low)
chk("I7 idempotent (re-runnable)", low.count("if not exists") >= 1)
chk("I8 number 255 is in this agent's band and is NOT already taken",
    not any(f.startswith("255_") and f != os.path.basename(MIG)
            for f in os.listdir(os.path.join(REPO, "database", "migrations"))))
try:
    import pglast
    pglast.parse_sql(body)
    chk("I9 real PostgreSQL parse (pglast)", True)
except ImportError:
    print("  skip I9 (pglast not installed)")
except Exception as e:
    chk("I9 real PostgreSQL parse (pglast)", False, str(e)[:120])
chk("I10 the DEFAULTS in code and the shape documented in the migration agree",
    all(k in sql for k in ("cost_equals_price", "cost_negative", "cost_zero", "gp_negative",
                           "rate_max", "min_ext_price")))


print("\n" + "=" * 78)
print(f"RESULT: {OK} passed, {FAIL} failed")
if FAILS:
    print("FAILED:", *FAILS, sep="\n  - ")
sys.exit(1 if FAIL else 0)
