"""GENERATED — do not hand-edit except the human fields named below.

    python3 backend/harness_data_qa_catalog.py --bless

One entry per report in `frontend/src/lib/reports.ts`: the report's own label and description become
the question, its page's own data endpoint becomes what is read, and the endpoint's own parameters
become what may be filtered. Derived so that a report shipped tomorrow is answerable tomorrow —
`harness_data_qa_catalog.py` FAILS THE BUILD when this file and the reports disagree (index 54.11).

HUMAN FIELDS, preserved across a re-bless:
  · `path`    — an override, when the rule picked the wrong one of a page's endpoints (`also` lists
                the ones it did not pick).
  · `skip`    — THE REASON this report answers no question. A sentence, never a bare flag.
  · `answers` — a rewording, when the report's description does not read as a question.

Everything else is recomputed. Pure data: stdlib only, no imports, so the semantic layer stays
provable with no database.
"""
SCHEMA = 1

DERIVED = [
    {
        'key': 'commcalc',
        'label': 'Commissions Dashboard',
        'answers': '',
        'page': '/commcalc',
        'path': '/api/v1/commcalc/commissions/{period}',
        'picked': '/api/v1/commcalc/commissions/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/commcalc/commission-plans/pay-warnings'],
        'hand': True,
    },
    {
        'key': 'commcalc_exec',
        'label': 'Owner Overview',
        'answers': '',
        'page': '/commcalc/exec',
        'path': '/api/v1/commcalc/exec-overview/{period}',
        'picked': '/api/v1/commcalc/exec-overview/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_activations',
        'label': 'Activations',
        'answers': 'POS Activation Details basis of truth — distinct devices by market/store, Upgrade toggle, and automatic reconciliation against the sales feed',
        'page': '/commcalc/activations',
        'path': '/api/v1/commcalc/activation-counts/{period}',
        'picked': '/api/v1/commcalc/activation-counts/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'as_of': 'date'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/commcalc/metric-recon'],
        'hand': True,
    },
    {
        'key': 'commcalc_schematic',
        'label': 'System Schematic',
        'answers': 'Data-lineage map: how ingested data and metrics feed each other, with code references and plain-English effects',
        'page': '/commcalc/schematic',
        'path': '/api/v1/commcalc/data-lineage',
        'picked': '/api/v1/commcalc/data-lineage',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_reports_index',
        'label': 'Reports Index',
        'answers': 'A searchable directory of every report on the platform — what each shows, who can see it, and whether it is live for you and what data feeds it',
        'page': '/commcalc/reports-index',
        'path': '/api/v1/commcalc/data-readiness',
        'picked': '/api/v1/commcalc/data-readiness',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_onboarding',
        'label': 'Setup Wizard',
        'answers': 'Guided onboarding: every data feed & config the platform needs, whether it is set up for you, and where to complete each one',
        'page': '/commcalc/onboarding',
        'path': '/api/v1/commcalc/onboarding',
        'picked': '/api/v1/commcalc/onboarding',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/data-readiness'],
        'hand': True,
    },
    {
        'key': 'commcalc_integrations',
        'label': 'Integrations',
        'answers': 'One page for every data connection & import — plain-English purpose, live connected/not-set-up status, and a 2-step setup wizard for each',
        'page': '/commcalc/integrations',
        'path': '/api/v1/commcalc/integrations',
        'picked': '/api/v1/commcalc/integrations',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/ingest-freshness'],
        'hand': True,
    },
    {
        'key': 'commcalc_gp',
        'label': 'Gross Profit',
        'answers': '',
        'page': '/commcalc/gp',
        'path': '/api/v1/commcalc/gp/{period}',
        'picked': '/api/v1/commcalc/gp/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/commcalc/commission-leg-trend', '/api/v1/commcalc/gp-trend'],
        'hand': True,
    },
    {
        'key': 'commcalc_kpi',
        'label': 'KPI Metrics',
        'answers': '',
        'page': '/commcalc/kpi',
        'path': '/api/v1/commcalc/kpi-actuals',
        'picked': '/api/v1/commcalc/kpi-actuals',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/carrier-kpi-metrics', '/api/v1/commcalc/commissions', '/api/v1/commcalc/dlar-store', '/api/v1/commcalc/kpi-import/paramount'],
        'hand': True,
    },
    {
        'key': 'commcalc_kpi_failing',
        'label': 'Failing KPIs',
        'answers': 'High-level overview of every KPI below target — org, market and store grain with rep drill-down',
        'page': '/commcalc/kpi-failing',
        'path': '/api/v1/commcalc/kpi-failing/{period}',
        'picked': '/api/v1/commcalc/kpi-failing/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_zero_sales',
        'label': 'Zero Sales',
        'answers': '',
        'page': '/commcalc/zero-sales',
        'path': '/api/v1/commcalc/zero-sales',
        'picked': '/api/v1/commcalc/zero-sales',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'date_from': 'date', 'date_to': 'date', 'store': 'store_code', 'rep': 'person'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_coaching',
        'label': 'Rep Coaching',
        'answers': '',
        'page': '/commcalc/coaching',
        'path': '/api/v1/commcalc/coaching/{period}',
        'picked': '/api/v1/commcalc/coaching/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'store': 'store_code', 'rep': 'person'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_sales_analyzer',
        'label': 'Retention Analysis',
        'answers': '3-month retention by rep/store — cohort retained vs churned, driven by whether the month-3 residual was paid',
        'page': '/commcalc/sales-analyzer',
        'path': '/api/v1/commcalc/sales-analyzer/{period}',
        'picked': '/api/v1/commcalc/sales-analyzer/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'rep': 'person'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/commcalc/chargeback-review'],
        'hand': True,
    },
    {
        'key': 'commcalc_sales_comparison',
        'label': 'Sales Comparison',
        'answers': 'Month-over-month / year-over-year % change per item sold (phones, BYOD, accessories, tablets, financing) across all stores',
        'page': '/commcalc/sales-comparison',
        'path': '/api/v1/commcalc/sales-comparison',
        'picked': '/api/v1/commcalc/sales-comparison',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_peer_comparison',
        'label': 'Peer Sales Comparison',
        'answers': 'Stores grouped by bill-payment volume — the measure of people through the door — then compared on total boxes (with the new / port / BYOD / upgrade / swap / tablet split), add-a-line, family plan %, accessory $ and accessory $ per box. Within a band the footfall is the same, so a gap is sell-through rather than location; each store is scored against its own band median and best.',
        'page': '/commcalc/peer-comparison',
        'path': '/api/v1/commcalc/peer-comparison',
        'picked': '/api/v1/commcalc/peer-comparison',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'targets_report_cards',
        'label': 'Manager Report Cards',
        'answers': 'Every item assigned to a district manager for each of their stores — the four target categories, conversion, and keeping up with stores of the same footfall — each one checked off by the system as met, missed, or no target set, and scored over the items that actually had a target. The card below it rolls the same check-off up to the manager above, a row per district manager, so accountability does not stop at the district. A store the org tree cannot place is listed separately with the reason, never dropped and never given a guessed owner.',
        'page': '/commcalc/targets/report-cards',
        'path': '/api/v1/commcalc/targets/{period}/report-cards',
        'picked': '/api/v1/commcalc/targets/{period}/report-cards',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_spiff_impact',
        'label': 'Spiff Impact',
        'answers': 'Pick one carrier pay type and see, per store, what it is worth to the commission payout revenue (its share of the P&L line it actually books to), by how much it raises net profit (profit with it against profit without it, from the stored per-store P&L), and which stores are not earning it on the boxes they sell — ranked inside each store’s own bill-payment traffic band, so the gap is sell-through and not footfall.',
        'page': '/commcalc/spiff-impact',
        'path': '/api/v1/commcalc/spiff-impact',
        'picked': '/api/v1/commcalc/spiff-impact',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_month_focus',
        'label': 'This Month’s Focus',
        'answers': 'What this month is about, declared at the start of it by a market manager or above: the focus in their own words, which carrier pay type is driving the month’s spiffs, the temporary spiffs on the table with their rate and window, and a note on targets. The page also says what the month still owes — the weekly check-in, the stores with no saved target, and any declared spiff the pay config does not actually carry, or any spiff being paid that the month never named. Each suggestion in the plays panel is a rule over a measured number and shows the figure behind it.',
        'page': '/commcalc/month-focus',
        'path': '/api/v1/commcalc/month-focus/{period}',
        'picked': '/api/v1/commcalc/month-focus/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_accessory_target_plan',
        'label': 'Accessory Target Allocation',
        'answers': 'Set one company accessory sales goal — a fixed total, or a % up or down from a named basis — and the report works out the target each store should carry, weighted by its own accessories-per-box over the last two months against the boxes it is projected to sell. Shows each of the last two months in its own column, month to date, the projected month-end, the target in force and the extension needed to meet the goal, then assigns the result to every store or just the ones picked from the multi-select. A store that sold boxes and attached nothing is weighted at the company rate and flagged, never given a $0 target.',
        'page': '/commcalc/accessory-target-plan',
        'path': '/api/v1/commcalc/accessory-target-plan/{period}',
        'picked': '/api/v1/commcalc/accessory-target-plan/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_product_mix',
        'label': 'Product Mix & Ports',
        'answers': 'What each store and each rep actually sold — which handset, and what the customer paid for it, banded free / budget / mid / premium — set against accessory $ per box and the share of their boxes that ported in. A rep is flagged only when BOTH are below the median of the reps in view, because the two signals correlate only weakly and a blended score would hide the rep who ports well and attaches nothing. Shows the carrier\\u2019s own port-in rate per store beside ours, measures the relationship between the cheap-device share and both outcomes every run rather than assuming it, and hands the lagging stores to the Peer Sales Comparison\\u2019s own band, median and coaching sentence so this screen and the action plan name the same stores.',
        'page': '/commcalc/product-mix',
        'path': '/api/v1/commcalc/product-mix',
        'picked': '/api/v1/commcalc/product-mix',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'store': 'store_code'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_comp_trend',
        'label': 'Total Compensation',
        'answers': '',
        'page': '/commcalc/comp-trend',
        'path': '/api/v1/commcalc/comp/rep-pay-trend',
        'picked': '/api/v1/commcalc/comp/rep-pay-trend',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'store': 'store_code'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/comp/residual-trend'],
        'hand': True,
    },
    {
        'key': 'commcalc_flags',
        'label': 'Flags',
        'answers': '',
        'page': '/commcalc/flags',
        'path': '/api/v1/commcalc/flags/{period}',
        'picked': '/api/v1/commcalc/flags/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_chargebacks',
        'label': 'Chargebacks & Fraud',
        'answers': '',
        'page': '/commcalc/chargebacks',
        'path': '/api/v1/commcalc/chargeback-review',
        'picked': '/api/v1/commcalc/chargeback-review',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'store': 'store_code'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/storeops/employees'],
        'hand': True,
    },
    {
        'key': 'commcalc_accessory_flags',
        'label': 'Accessory Flags',
        'answers': '',
        'page': '/commcalc/accessory-flags',
        'path': '/api/v1/commcalc/accessory-flags',
        'picked': '/api/v1/commcalc/accessory-flags',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'start': 'date', 'end': 'date', 'store': 'store_code', 'rep': 'person', 'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/accessory-flags/push', '/api/v1/commcalc/accessory-flags/receipt', '/api/v1/commcalc/flag-rules'],
        'hand': True,
    },
    {
        'key': 'commcalc_commission_withholding',
        'label': 'Commission Withholding',
        'answers': 'Every activation the carrier took commission back on, with what was taken, whether commission landed against the same activation in a later month and in which months, the processor payment actually made against it shown in parallel and never netted against the clawback, and the appeal state a manager set. An activation that could not be looked up is reported as not known, never as a loss.',
        'page': '/commcalc/commission-withholding',
        'path': '/api/v1/commcalc/commission-withholding',
        'picked': '/api/v1/commcalc/commission-withholding',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'store': 'store_code', 'rep': 'person'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_discrepancy',
        'label': 'Pay Discrepancy',
        'answers': 'Underpaid / unpaid activations per month — the carrier bounty gap engine, plus POS activations verified against the payment processor\'s commission feeds: sold-but-unpaid rows attributed via uploadable business rules, or flagged "no business rule configured"',
        'page': '/commcalc/discrepancy',
        'path': '/api/v1/commcalc/discrepancy/{period}',
        'picked': '/api/v1/commcalc/discrepancy/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_imei_rebates',
        'label': 'IMEI Rebate Reconciliation',
        'answers': '',
        'page': '/commcalc/imei-rebates',
        'path': '/api/v1/commcalc/imei-rebates',
        'picked': '/api/v1/commcalc/imei-rebates',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_carrier_vs_pay',
        'label': 'Carrier Earned vs Employee Paid',
        'answers': '',
        'page': '/commcalc/carrier-vs-pay',
        'path': '/api/v1/commcalc/carrier-vs-pay/{period}',
        'picked': '/api/v1/commcalc/carrier-vs-pay/{period}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'store': 'store_code'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_vendor_rebates',
        'label': 'Vendor Rebate History (earned, per line)',
        'answers': 'Every rebate/commission line the carrier statement says it OWES, landed per component. Earned and Collected are reported separately and never summed — this feed proves no payment and books nothing to the P&L, GP or payout.',
        'page': '/commcalc/vendor-rebates',
        'path': '/api/v1/commcalc/vendor-rebates',
        'picked': '/api/v1/commcalc/vendor-rebates',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'store': 'store_code'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_ma_handsets',
        'label': 'Marketplace Handset COGS',
        'answers': '',
        'page': '/commcalc/ma-handsets',
        'path': '/api/v1/commcalc/ma-handset-cogs',
        'picked': '/api/v1/commcalc/ma-handset-cogs',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_device_cost_recon',
        'label': 'Device Cost Reconciliation',
        'answers': '',
        'page': '/commcalc/device-cost-recon',
        'path': '/api/v1/commcalc/device-cost-recon',
        'picked': '/api/v1/commcalc/device-cost-recon',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_sales_recon',
        'label': 'Sales Feed Recon',
        'answers': '',
        'page': '/commcalc/sales-recon',
        'path': '/api/v1/commcalc/sales-recon',
        'picked': '/api/v1/commcalc/sales-recon',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/sales-recon/sync-flags', '/api/v1/commcalc/sales-recon/transaction'],
        'hand': True,
    },
    {
        'key': 'watchdog',
        'label': 'Management Watchdog',
        'answers': 'Every finding the platform raises, grouped by the part of the business you would go and act on — cash and closing, voids and returns, sales against commission, fraud, port-outs, inventory, distributor, and feed integrity. Each area opens its own report. A finding stays until somebody rules on it and clears itself when its cause is fixed; nothing is deleted, so the decision trail survives. An area with nothing open says so in words rather than showing a bare 0, and a finding whose kind is not registered is counted under Unclassified rather than hidden.',
        'page': '/watchdog',
        'path': '/api/v1/commcalc/watchdog/board',
        'picked': '/api/v1/commcalc/watchdog/board',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_cash',
        'label': 'Watchdog · Cash & Closing',
        'answers': "Drawer and card variances on store-days that were accepted, waved through on the final try while still mismatched, or submitted and never corrected — plus the same person turning up on repeated variance days. Every figure is the close gate's OWN recorded comparison, never recomputed, and a store-day the sales feed never carried shows no variance rather than a fabricated zero.",
        'page': '/watchdog/cash',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'cash'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_voids',
        'label': 'Watchdog · Voids, Returns & Waived Fees',
        'answers': "Reversed and returned transactions above the allowed share, one device both sold and voided, voided lines carrying nobody's name, and activations with no setup fee charged. The classification is the commission path's own rule read a second way, so what counts as a void here is what counts as a void for pay.",
        'page': '/watchdog/voids',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'voids'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_void_register',
        'label': 'Void & Return Register',
        'answers': 'Every voided, returned and unnamed sales line for the period, with the rate by person and by store. These lines are already excluded from commission and gross profit — this is the first place they are counted rather than only thrown away. A rate reads "—", never 0%, where there were no lines to measure.',
        'page': '/watchdog/void-register',
        'path': '/api/v1/commcalc/watchdog/voids',
        'picked': '/api/v1/commcalc/watchdog/voids',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_commission',
        'label': 'Watchdog · Sales vs Commission',
        'answers': 'Sales the commission feed never carried, sales paid at an amount that does not match the sale, commission clawed back, and installments withheld because the line stopped paying.',
        'page': '/watchdog/commission',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'commission'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_fraud',
        'label': 'Watchdog · Fraud & Identity',
        'answers': 'One device used on several lines, and activation patterns that do not look like retail selling.',
        'page': '/watchdog/fraud',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'fraud'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_churn',
        'label': 'Watchdog · Port-outs & Churn',
        'answers': 'Subscribers that ported out, were transferred to another dealer, or were suspended for non-payment, banded by how soon after the sale.',
        'page': '/watchdog/churn',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'churn'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_device_line_reimbursement',
        'label': 'Reimbursement per Line',
        'answers': 'One row per device the distributor claims a reimbursement for: what it claimed, what the device cost, what the store charged for it, and what the carrier’s own per-line feed actually paid — at this store and at any other. A device the carrier paid a DIFFERENT store for is its own verdict and never counted as unpaid, because the distributor books the claim to the store the device was stocked to while the carrier pays the store it was activated at. A device with nothing paid anywhere in a month whose statement arrived short is reported not measured with the missing days named, never as “never paid”. Reads the carrier side one month either side of the claim, because the distributor settles after the carrier pays as often as before it.',
        'page': '/commcalc/device-line-reimbursement',
        'path': '/api/v1/commcalc/device-line-reimbursement',
        'picked': '/api/v1/commcalc/device-line-reimbursement',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period', 'store': 'store_code'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': False,
    },
    {
        'key': 'watchdog_inventory',
        'label': 'Watchdog · Inventory & Assets',
        'answers': 'Units the ledger and the shelf disagree about, devices reimbursed below the published rate, returns never credited, and devices sold below cost.',
        'page': '/watchdog/inventory',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'inventory'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_distributor',
        'label': 'Watchdog · Distributor & Payables',
        'answers': 'Invoices due and overdue, credit memos that do not reconcile, and rebates earned but never received.',
        'page': '/watchdog/distributor',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'distributor'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'watchdog_feed',
        'label': 'Watchdog · Feed & Data Integrity',
        'answers': 'A store or payment type the platform received data for but cannot place — a gap that makes every other number for that store wrong.',
        'page': '/watchdog/feed',
        'path': '/api/v1/commcalc/watchdog/area/{area}',
        'picked': '/api/v1/commcalc/watchdog/area/{area}',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {'area': 'feed'},
        'also': [],
        'hand': True,
    },
    {
        'key': 'compliance',
        'label': 'Flags & Compliance Dashboard',
        'answers': 'Per-queue open counts across every flag, exception and compliance queue on the platform — each count is the same query as the page that owns the queue, and a probe that fails shows "—" rather than a fake 0',
        'page': '/compliance',
        'path': '/api/v1/commcalc/compliance-summary',
        'picked': '/api/v1/commcalc/compliance-summary',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/nav-config', '/api/v1/commcalc/tile-layout'],
        'hand': True,
    },
    {
        'key': 'commcalc_manager_followup',
        'label': 'Follow Up With Managers',
        'answers': 'Every pending job a manager owns, rolled up per store and queue with the age of the oldest — what has passed the escalation age reaches the manager above the owner too. Open items carrying no store are counted and named rather than dropped, and any queue that cannot yet be assigned per manager is listed with the reason, so the board is never read as "that is everything". A digest goes out daily at the configured time by WhatsApp and email.',
        'page': '/commcalc/manager-followup',
        'path': '/api/v1/commcalc/manager-followup',
        'picked': '/api/v1/commcalc/manager-followup',
        'override': None,
        'answers_override': None,
        'module': 'commissions',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_targets',
        'label': 'Daily Targets',
        'answers': '',
        'page': '/commcalc/targets',
        'path': '/api/v1/commcalc/targets/{period}',
        'picked': '/api/v1/commcalc/targets/{period}',
        'override': None,
        'answers_override': None,
        'module': 'targets',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'targets_action_plan',
        'label': 'Action Plan',
        'answers': '',
        'page': '/commcalc/targets/action-plan',
        'path': '/api/v1/commcalc/targets/{period}/action-plan',
        'picked': '/api/v1/commcalc/targets/{period}/action-plan',
        'override': None,
        'answers_override': None,
        'module': 'targets',
        'skip': None,
        'params': {'period': 'period', 'store_code': 'store_code', 'rep': 'person'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'targets_my',
        'label': 'My Targets',
        'answers': '',
        'page': '/commcalc/targets/my',
        'path': '/api/v1/commcalc/targets/{period}',
        'picked': '/api/v1/commcalc/targets/{period}',
        'override': None,
        'answers_override': None,
        'module': 'targets',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'storeops_team',
        'label': 'My Team',
        'answers': '',
        'page': '/storeops/team',
        'path': '/api/v1/storeops/org/tree',
        'picked': '/api/v1/storeops/org/tree',
        'override': None,
        'answers_override': None,
        'module': 'storeops',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'commcalc_asset',
        'label': 'Assets',
        'answers': '',
        'page': '/commcalc/asset',
        'path': '/api/v1/asset/summary',
        'picked': '/api/v1/asset/summary',
        'override': None,
        'answers_override': None,
        'module': 'asset',
        'skip': None,
        'params': {'store': 'store_code', 'date_from': 'date', 'date_to': 'date'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/asset/backfill-selling-price', '/api/v1/asset/category-detail', '/api/v1/asset/resync-market'],
        'hand': True,
    },
    {
        'key': 'commcalc_vip',
        'label': 'Distributor Invoices',
        'answers': '',
        'page': '/commcalc/vip',
        'path': '/api/v1/commcalc/vip/summary',
        'picked': '/api/v1/commcalc/vip/summary',
        'override': None,
        'answers_override': None,
        'module': 'vip',
        'skip': None,
        'params': {'period': 'period', 'location': 'store_code', 'date_from': 'date', 'date_to': 'date'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/vip/invoices'],
        'hand': True,
    },
    {
        'key': 'accounts',
        'label': 'Accounts Dashboard',
        'answers': '',
        'page': '/accounts',
        'path': '/api/v1/account/overview/{period}',
        'picked': '/api/v1/core/markets',
        'override': '/api/v1/account/overview/{period}',
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/account/overview'],
        'hand': True,
    },
    {
        'key': 'accounts_pl',
        'label': 'P&L Statement',
        'answers': '',
        'page': '/accounts/pl',
        'path': '/api/v1/account/overview/{period}',
        'picked': '/api/v1/account/overview/{period}',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'accounts_balance_sheet',
        'label': 'Balance Sheet',
        'answers': '',
        'page': '/accounts/balance-sheet',
        'path': '/api/v1/account/balance-sheet/{period}',
        'picked': '/api/v1/account/balance-sheet/{period}',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/account/inventory-values', '/api/v1/account/overview'],
        'hand': True,
    },
    {
        'key': 'accounts_recon',
        'label': 'Reconciliation',
        'answers': '',
        'page': '/accounts/recon',
        'path': '/api/v1/account/recon/{period}',
        'picked': '/api/v1/account/recon/{period}',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/account/credit-memos/sweep'],
        'hand': True,
    },
    {
        'key': 'accounts_residual_per_sub',
        'label': 'Residual per Subscriber',
        'answers': '',
        'page': '/accounts/residual-per-sub',
        'path': '/api/v1/account/residual-per-sub',
        'picked': '/api/v1/account/residual-per-sub',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'accounts_trends',
        'label': 'Trends (all metrics)',
        'answers': '',
        'page': '/accounts/trends',
        'path': '/api/v1/commcalc/gp-trend',
        'picked': '/api/v1/commcalc/gp-trend',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/account/residual-per-sub', '/api/v1/commcalc/commission-trend', '/api/v1/commcalc/expenses-trend'],
        'hand': True,
    },
    {
        'key': 'accounts_analysis',
        'label': 'Financial Analysis (charts · projections · valuation)',
        'answers': '',
        'page': '/accounts/analysis',
        'path': '/api/v1/account/analysis',
        'picked': '/api/v1/account/analysis',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/account/projection', '/api/v1/account/valuation'],
        'hand': True,
    },
    {
        'key': 'accounts_cash_flow',
        'label': 'Cash Flow Statement',
        'answers': '',
        'page': '/accounts/cash-flow',
        'path': '/api/v1/account/cash-flow/{period}',
        'picked': '/api/v1/account/cash-flow/{period}',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': ['period'],
        'bound': {},
        'also': ['/api/v1/account/overview'],
        'hand': True,
    },
    {
        'key': 'accounts_liabilities_due',
        'label': 'Current Monetary Liabilities',
        'answers': 'Owed to distributor, payments due this week, payroll & payroll tax due, rents and recurring expenses due — per store',
        'page': '/accounts/liabilities-due',
        'path': '/api/v1/account/liabilities-due',
        'picked': '/api/v1/account/liabilities-due',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {'date': 'date'},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'accounts_device_purchases',
        'label': 'Device Purchases',
        'answers': 'Cost of every phone/device the distributor billed us in a period, segregated by company and by store. PURCHASES (what was billed) — deliberately separate from device COGS (what the units we sold cost us)',
        'page': '/accounts/device-purchases',
        'path': '/api/v1/account/device-purchases',
        'picked': '/api/v1/account/device-purchases',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'accounts_device_payable',
        'label': 'Device Payable as at a date',
        'answers': 'Of the devices already billed to us on a chosen day, which ones had not yet been paid for — by company and by store. A BACKDATED payable read from each unit\\u2019s own payment date, not from a current status; non-device items (chargebacks, fees, SIMs) are reported separately on a billed basis',
        'page': '/accounts/device-payable',
        'path': '/api/v1/account/device-payable',
        'picked': '/api/v1/account/device-payable',
        'override': None,
        'answers_override': None,
        'module': 'accounts',
        'skip': None,
        'params': {},
        'path_params': [],
        'bound': {},
        'also': [],
        'hand': True,
    },
    {
        'key': 'storeops_reports',
        'label': 'Hours / Payroll Reports',
        'answers': '',
        'page': '/storeops/reports',
        'path': '/api/v1/storeops/payroll',
        'picked': '/api/v1/storeops/payroll',
        'override': None,
        'answers_override': None,
        'module': 'storeops',
        'skip': None,
        'params': {'month': 'period', 'start': 'date', 'end': 'date'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/storeops/payroll/over-hours'],
        'hand': True,
    },
    {
        'key': 'storeops_payroll',
        'label': 'Payroll',
        'answers': '',
        'page': '/storeops/payroll',
        'path': '/api/v1/storeops/payroll',
        'picked': '/api/v1/storeops/payroll',
        'override': None,
        'answers_override': None,
        'module': 'storeops',
        'skip': None,
        'params': {'month': 'period', 'start': 'date', 'end': 'date'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/storeops/employees', '/api/v1/storeops/payroll/over-hours'],
        'hand': True,
    },
    {
        'key': 'closing',
        'label': 'Closing Dashboard',
        'answers': '',
        'page': '/closing',
        'path': '/api/v1/closing/rollup',
        'picked': '/api/v1/closing/rollup',
        'override': None,
        'answers_override': None,
        'module': 'closing',
        'skip': None,
        'params': {'period': 'period', 'date_from': 'date', 'date_to': 'date'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/closing/readiness', '/api/v1/storeops/employees'],
        'hand': True,
    },
    {
        'key': 'closing_recon',
        'label': 'Closing Reconciliation',
        'answers': '',
        'page': '/closing/recon',
        'path': '/api/v1/closing/recon',
        'picked': '/api/v1/closing/recon',
        'override': None,
        'answers_override': None,
        'module': 'closing',
        'skip': None,
        'params': {'period': 'period'},
        'path_params': [],
        'bound': {},
        'also': ['/api/v1/commcalc/chargeback-review'],
        'hand': True,
    },
]
