// GENERATED — do not edit the ROUTES array by hand.
//
// THE ONE HOME for "every page this app has". Derived by walking `src/app` with
// `node frontend/prove_route_index.mjs --bless`; the same file run WITHOUT `--bless` is the proof,
// and it FAILS THE BUILD when disk and this array disagree. That ratchet is the whole point: before
// it, 34 of 319 static pages were in no registry at all and therefore unfindable by any search in the
// product — including the one somebody actually asked for, `/account/password`. Curating the missing
// page would have left the other 33, so the registry is derived instead (the `module_graph.py`
// pattern, §50).
//
// FOUR FIELDS ARE HUMAN and are PRESERVED across a re-bless:
//   label    — ONLY for a page the nav does not list, since the nav's own label is what the viewer
//              sees for every page it does. A derived label reads like a path ("Account → Password");
//              replace it with what people call the page.
//   aliases  — the words somebody would TYPE. For a page nav lists, aliases belong in
//              `ScreenLink.tsx` SCREENS instead: its guard requires every href to be a nav href,
//              which is mechanically why a page like `/account/password` can only declare them here.
//   preauth  — the REASON a page is deliberately not searchable (a sign-in screen, a public terms
//              page). Not a flag: the string is the reason, so an exclusion cannot be silent.
//   menuless — the REASON a page is deliberately in no menu. Same shape as `preauth` and for the
//              same reason: 27 pages were menu-less by ACCIDENT, and before §54.12 that also made
//              them unfindable in the sidebar's ⌘K box, which indexed the nav alone. Both boxes now
//              search this registry, so a menu-less page is findable either way — but being in no
//              menu is a decision, and §I fails the build when a NEW one is made silently.
//
// A COMMENT INSIDE THE ARRAY DOES NOT SURVIVE A BLESS — the renderer emits one line per entry and
// nothing else, so a note written between entries is dropped the next time anyone runs `--bless`.
// Put the reason in the entry itself (`preauth`, `menuless`) or in this header, where it lasts.
//
// Everything else about a page — may this viewer open it, what module gates it — stays where it
// already lives (`rbac.canAccessPath`, `canSeeItem`). This file says only WHAT EXISTS.
export type RouteEntry = {
  path: string
  /** What people call the page — present ONLY for a page the nav does not list, because for every
   *  other page the nav's own label is the wording on the viewer's screen and a second copy here
   *  could only ever disagree with it (and, derived from the path, leak the other carrier side's
   *  vocabulary into display copy — which is how this rule was found). */
  label?: string
  aliases?: string[]
  /** Why this page is deliberately not offered by search. Absent = searchable. */
  preauth?: string
  /** Why this page is deliberately in no menu. Absent and not on §I's baseline = the build is red,
   *  so a page cannot fall out of the nav unnoticed. Findability does not depend on it: both search
   *  boxes read this registry (§54.12). */
  menuless?: string
}

export const ROUTES: RouteEntry[] = [
  { path: '/', label: 'Home', preauth: 'the marketing root — a signed-in user is redirected away from it' },
  { path: '/account/password', label: 'My Password', aliases: ['password reset', 'reset password', 'change password', 'change my password', 'forgot password', 'new password'], menuless: 'reached from the account menu under the avatar (layout.tsx) and forced on a must_reset_password login — personal, not a module, so it belongs in neither the sidebar nor a report category' },
  { path: '/accounts' },
  { path: '/accounts/analysis' },
  { path: '/accounts/balance-sheet' },
  { path: '/accounts/cash-flow' },
  { path: '/accounts/companies' },
  { path: '/accounts/cost-centers' },
  { path: '/accounts/device-payable' },
  { path: '/accounts/device-purchases' },
  { path: '/accounts/inventory' },
  { path: '/accounts/journal' },
  { path: '/accounts/liabilities-due' },
  { path: '/accounts/pl' },
  { path: '/accounts/profit-centers' },
  { path: '/accounts/recon' },
  { path: '/accounts/residual-per-sub' },
  { path: '/accounts/royalty' },
  { path: '/accounts/royalty/recon' },
  { path: '/accounts/trends' },
  { path: '/admin/access-log' },
  { path: '/admin/billing' },
  { path: '/admin/billing-usage' },
  { path: '/admin/business-types' },
  { path: '/admin/carrier-documents' },
  { path: '/admin/control-box' },
  { path: '/admin/dashboards' },
  { path: '/admin/fix-requests' },
  { path: '/admin/impersonation' },
  { path: '/admin/import-health' },
  { path: '/admin/kpi-metrics' },
  { path: '/admin/labels' },
  { path: '/admin/menu' },
  { path: '/admin/org' },
  { path: '/admin/org-chart' },
  { path: '/admin/pricing' },
  { path: '/admin/roles' },
  { path: '/admin/security' },
  { path: '/admin/support' },
  { path: '/admin/support/docs' },
  { path: '/admin/support/failures' },
  { path: '/admin/support/fix-requests' },
  { path: '/admin/tenant-settings' },
  { path: '/admin/tenants' },
  { path: '/admin/training' },
  { path: '/admin/whats-new' },
  { path: '/approvals' },
  { path: '/chat' },
  { path: '/closing' },
  { path: '/closing/accessory-recon' },
  { path: '/closing/accountability' },
  { path: '/closing/billpay-pickup' },
  { path: '/closing/cash-config' },
  { path: '/closing/cash-position', label: 'Cash Position', aliases: ['cash on hand', 'cash position'] },
  { path: '/closing/cash-recon-management' },
  { path: '/closing/count-config', label: 'Cash Count Setup', aliases: ['count config', 'denomination count'] },
  { path: '/closing/deposit-categories' },
  { path: '/closing/deposit-recon' },
  { path: '/closing/duplicates', label: 'Duplicate Closings', aliases: ['duplicate closing', 'double closing'] },
  { path: '/closing/envelope-config' },
  { path: '/closing/envelope-payout' },
  { path: '/closing/envelope-report' },
  { path: '/closing/epay-recon' },
  { path: '/closing/expense-categories' },
  { path: '/closing/expenses-report' },
  { path: '/closing/external-credit-recon' },
  { path: '/closing/imports' },
  { path: '/closing/management' },
  { path: '/closing/pickup' },
  { path: '/closing/readiness', label: 'Closing Readiness', aliases: ['closing readiness', 'which stores closed'] },
  { path: '/closing/recon' },
  { path: '/closing/store-cash-on-hand' },
  { path: '/closing/store-visit-config', label: 'Store Visit Setup', aliases: ['store visit config', 'visit schedule setup'] },
  { path: '/closing/submit' },
  { path: '/closing/tender-config' },
  { path: '/closing/tender-recon' },
  { path: '/closing/tender-recon-3way' },
  { path: '/closing/verify' },
  { path: '/commcalc' },
  { path: '/commcalc/accessory-cost-audit' },
  { path: '/commcalc/accessory-definition' },
  { path: '/commcalc/accessory-flags' },
  { path: '/commcalc/activations' },
  { path: '/commcalc/agency' },
  { path: '/commcalc/asset' },
  { path: '/commcalc/asset/aging' },
  { path: '/commcalc/asset/aging-rebate' },
  { path: '/commcalc/asset/borrowed' },
  { path: '/commcalc/asset/charges/rma' },
  { path: '/commcalc/asset/dashboard' },
  { path: '/commcalc/asset/hotsheet-recon' },
  { path: '/commcalc/asset/inventory-recon' },
  { path: '/commcalc/asset/invoice-due', label: 'Invoices Due', aliases: ['invoice due', 'what do i owe'] },
  { path: '/commcalc/asset/lending' },
  { path: '/commcalc/asset/marketplace-purchases' },
  { path: '/commcalc/asset/missing-phones' },
  { path: '/commcalc/asset/on-inventory' },
  { path: '/commcalc/asset/oninv-3way-recon', label: 'Three-Way Invoice Match', aliases: ['3 way match', 'invoice reconciliation', 'oninv recon'] },
  { path: '/commcalc/asset/owed-weekly' },
  { path: '/commcalc/asset/purchase-orders' },
  { path: '/commcalc/asset/purchase-orders/aging', label: 'Purchase Order Aging', aliases: ['po aging', 'old purchase orders'] },
  { path: '/commcalc/asset/purchase-orders/receiving', label: 'Receive a Purchase Order', aliases: ['receiving', 'receive stock', 'po receiving'] },
  { path: '/commcalc/asset/purchase-orders/tally', label: 'Purchase Order Tally', aliases: ['po tally'] },
  { path: '/commcalc/asset/purchase-orders/vendors', label: 'Purchase Order Vendors', aliases: ['po vendors', 'supplier list'] },
  { path: '/commcalc/atu-opportunity' },
  { path: '/commcalc/bill-payments' },
  { path: '/commcalc/carrier-comm-file' },
  { path: '/commcalc/carrier-mapping' },
  { path: '/commcalc/carrier-recon' },
  { path: '/commcalc/carrier-vs-pay' },
  { path: '/commcalc/catalog' },
  { path: '/commcalc/chargebacks' },
  { path: '/commcalc/coaching' },
  { path: '/commcalc/column-mapping' },
  { path: '/commcalc/commission-category-map' },
  { path: '/commcalc/commission-discrepancy' },
  { path: '/commcalc/commission-explain', label: 'Why This Commission', aliases: ['explain commission', 'how was this paid', 'commission explain'], menuless: 'the menu-less carrier diagnostic — reached from a payout row, never browsed to (§54.7, and harness_payout_audience_lock §i2 holds its audience)' },
  { path: '/commcalc/commission-import' },
  { path: '/commcalc/commission-ledger' },
  { path: '/commcalc/commission-ledger/setup', label: 'Commission Ledger Setup', aliases: ['ledger setup', 'commission ledger mapping'] },
  { path: '/commcalc/commission-legs' },
  { path: '/commcalc/commission-plans' },
  { path: '/commcalc/commission-structure' },
  { path: '/commcalc/commission-withholding' },
  { path: '/commcalc/comp-trend' },
  { path: '/commcalc/connectors' },
  { path: '/commcalc/custom-report' },
  { path: '/commcalc/daily-commission' },
  { path: '/commcalc/device-cost-recon' },
  { path: '/commcalc/device-history' },
  { path: '/commcalc/discrepancy' },
  { path: '/commcalc/distributors' },
  { path: '/commcalc/dlar-vs-platform' },
  { path: '/commcalc/dlar/sweep' },
  { path: '/commcalc/email-imports' },
  { path: '/commcalc/epay-fee-recon' },
  { path: '/commcalc/epay/sweep' },
  { path: '/commcalc/exec' },
  { path: '/commcalc/exec/mtd' },
  { path: '/commcalc/expected-commission' },
  { path: '/commcalc/expenses' },
  { path: '/commcalc/financing' },
  { path: '/commcalc/financing/vendors', label: 'Financing Vendors', aliases: ['financing vendors', 'lease vendors'] },
  { path: '/commcalc/flags' },
  { path: '/commcalc/ftp-imports' },
  { path: '/commcalc/gp' },
  { path: '/commcalc/gp-category-map' },
  { path: '/commcalc/imei-rebates' },
  { path: '/commcalc/imei-recon' },
  { path: '/commcalc/implementation' },
  { path: '/commcalc/ingest-guard' },
  { path: '/commcalc/integrations' },
  { path: '/commcalc/inventory-sold-recon' },
  { path: '/commcalc/item-mapping' },
  { path: '/commcalc/kpi' },
  { path: '/commcalc/kpi-failing' },
  { path: '/commcalc/ma-class-wiring', label: 'Master Agent Class Wiring', aliases: ['ma class wiring', 'class wiring'] },
  { path: '/commcalc/ma-commission' },
  { path: '/commcalc/ma-handsets' },
  { path: '/commcalc/ma-overview-recon' },
  { path: '/commcalc/ma-product-class' },
  { path: '/commcalc/ma-upload', label: 'Upload a Master Agent Statement', aliases: ['ma upload', 'upload statement', 'master agent upload'] },
  { path: '/commcalc/management-incentive' },
  { path: '/commcalc/manager-followup' },
  { path: '/commcalc/mapping' },
  { path: '/commcalc/onboarding' },
  { path: '/commcalc/pay-simulator' },
  { path: '/commcalc/payables' },
  { path: '/commcalc/payout-plans' },
  { path: '/commcalc/payout-schedules' },
  { path: '/commcalc/peer-comparison', aliases: ['peer comparison', 'similar stores', 'bill payment band', 'traffic band', 'boxes per bill payment'] },
  { path: '/commcalc/plan-assignment-audit', label: 'Plan Assignment Audit', aliases: ['plan assignment', 'who is on which plan'] },
  { path: '/commcalc/plan-installments' },
  { path: '/commcalc/processor-ledger' },
  { path: '/commcalc/productivity' },
  { path: '/commcalc/productivity-insights' },
  { path: '/commcalc/recovery' },
  { path: '/commcalc/rep-aliases' },
  { path: '/commcalc/report-mappings', label: 'Report Column Mappings', aliases: ['report mappings', 'column mapping'] },
  { path: '/commcalc/reports' },
  { path: '/commcalc/reports-index' },
  { path: '/commcalc/sales-analyzer' },
  { path: '/commcalc/sales-comparison' },
  { path: '/commcalc/sales-derive', label: 'Derive Sales From the Feed', aliases: ['sales derive', 'derive sales'] },
  { path: '/commcalc/sales-recon' },
  { path: '/commcalc/sales-report' },
  { path: '/commcalc/schematic' },
  { path: '/commcalc/settings' },
  { path: '/commcalc/spiff-impact', aliases: ['spiff impact', 'spiff effect', 'which spiff', 'bounty impact', 'pay type impact', 'profit lift'] },
  { path: '/commcalc/store-match' },
  { path: '/commcalc/target-fields' },
  { path: '/commcalc/targets' },
  { path: '/commcalc/targets/accessories' },
  { path: '/commcalc/targets/action-plan' },
  { path: '/commcalc/targets/my' },
  { path: '/commcalc/targets/rep-map' },
  { path: '/commcalc/targets/report-cards', aliases: ['report card', 'report cards', 'dm scorecard', 'manager scorecard', 'dm accountability', 'targets met'] },
  { path: '/commcalc/targets/settings' },
  { path: '/commcalc/tax-collected' },
  { path: '/commcalc/upload' },
  { path: '/commcalc/upload/wizard' },
  { path: '/commcalc/vendor-rebates' },
  { path: '/commcalc/vip' },
  { path: '/commcalc/vip/paygo' },
  { path: '/commcalc/vip/sweep' },
  { path: '/commcalc/whatif' },
  { path: '/commcalc/zero-sales' },
  { path: '/compliance' },
  { path: '/configurations' },
  { path: '/crm' },
  { path: '/crm/agencies' },
  { path: '/crm/leads' },
  { path: '/crm/leads/new' },
  { path: '/crm/lookup' },
  { path: '/crm/my-followups' },
  { path: '/crm/pipeline' },
  { path: '/crm/reports' },
  { path: '/crm/settings' },
  { path: '/employee' },
  { path: '/failures' },
  { path: '/franchise' },
  { path: '/helpdesk' },
  { path: '/helpdesk/dashboard' },
  { path: '/helpdesk/new' },
  { path: '/helpdesk/settings' },
  { path: '/hr' },
  { path: '/hr/compliance' },
  { path: '/hr/employee-database' },
  { path: '/hr/letters' },
  { path: '/hr/letters/queue', label: 'Letters Waiting to Send', aliases: ['letter queue', 'letters waiting'] },
  { path: '/hr/letters/send', label: 'Send a Letter', aliases: ['send letter', 'write a letter'] },
  { path: '/hr/letters/sent', label: 'Letters Already Sent', aliases: ['sent letters', 'letter history'] },
  { path: '/hr/onboarding' },
  { path: '/hr/payroll-expenses' },
  { path: '/hr/people' },
  { path: '/login', label: 'Login', preauth: 'the sign-in screen — nobody searches for it from inside the app' },
  { path: '/marketing' },
  { path: '/marketing/events/new' },
  { path: '/marketing/my-checkins' },
  { path: '/marketing/sales-from-events' },
  { path: '/marketing/settings' },
  { path: '/notify' },
  { path: '/notify/report-recipients' },
  { path: '/onboarding/intake' },
  { path: '/operator' },
  { path: '/operator/audit' },
  { path: '/operator/billing' },
  { path: '/operator/notices' },
  { path: '/operator/operators' },
  { path: '/operator/tenants' },
  { path: '/payroll' },
  { path: '/portal', label: 'Employee Portal', aliases: ['portal', 'my portal'], menuless: 'the employee time-clock portal, outside the (platform) shell entirely — it has no module sidebar to be listed in, and a rep reaches it as their whole app rather than as a page' },
  { path: '/pos/activation-report' },
  { path: '/pos/activations' },
  { path: '/pos/customers' },
  { path: '/pos/import' },
  { path: '/pos/inventory' },
  { path: '/pos/onboarding' },
  { path: '/pos/products' },
  { path: '/pos/receipts' },
  { path: '/pos/reports' },
  { path: '/pos/sales' },
  { path: '/pos/settings' },
  { path: '/pos/special-orders' },
  { path: '/pos/special-orders/manage' },
  { path: '/pos/vendors' },
  { path: '/privacy', label: 'Privacy', preauth: 'a public policy page, not a place to do work' },
  { path: '/referral' },
  { path: '/referral/approvals' },
  { path: '/referral/list' },
  { path: '/referral/new' },
  { path: '/referral/settings' },
  { path: '/remediation' },
  { path: '/reports' },
  { path: '/signup', label: 'Signup', preauth: 'the sign-up screen — reached before there is an account' },
  { path: '/storeops' },
  { path: '/storeops/accountability' },
  { path: '/storeops/admin' },
  { path: '/storeops/attendance' },
  { path: '/storeops/closing', label: 'Store Closing', aliases: ['store closing', 'close the store'] },
  { path: '/storeops/dm-accessory-attribution', label: 'Accessory Attribution by Manager', aliases: ['dm accessory', 'accessory attribution'] },
  { path: '/storeops/employees' },
  { path: '/storeops/hours-budget' },
  { path: '/storeops/payroll' },
  { path: '/storeops/payroll-change-log', label: 'Payroll Change Log', aliases: ['payroll changes', 'who changed pay'] },
  { path: '/storeops/payroll-tax' },
  { path: '/storeops/payroll/approvals' },
  { path: '/storeops/payroll/payers' },
  { path: '/storeops/reports' },
  { path: '/storeops/reviews' },
  { path: '/storeops/reviews/config' },
  { path: '/storeops/salary-advances', label: 'Salary Advances', aliases: ['salary advance', 'pay advance', 'loan to employee'] },
  { path: '/storeops/schedule' },
  { path: '/storeops/setup/employees' },
  { path: '/storeops/setup/insurance' },
  { path: '/storeops/setup/stores' },
  { path: '/storeops/shift-extensions' },
  { path: '/storeops/staffing' },
  { path: '/storeops/swaps' },
  { path: '/storeops/team' },
  { path: '/storeops/timeclock' },
  { path: '/storeops/timeclock-permissions' },
  { path: '/storeops/timeoff' },
  { path: '/storeops/visits' },
  { path: '/storeops/visits/new', label: 'Log a Store Visit', aliases: ['new visit', 'log a visit', 'store visit'] },
  { path: '/storeops/visits/plan' },
  { path: '/storeops/visits/settings' },
  { path: '/supply/cart' },
  { path: '/supply/compare' },
  { path: '/supply/orders' },
  { path: '/supply/vendors' },
  { path: '/terms', label: 'Terms', preauth: 'a public policy page, not a place to do work' },
  { path: '/training' },
  { path: '/vision' },
  { path: '/vision/activity' },
  { path: '/vision/behavior' },
  { path: '/vision/busy-hours' },
  { path: '/vision/heatmap' },
  { path: '/vision/lines' },
  { path: '/vision/onboarding' },
  { path: '/vision/settings' },
  { path: '/watchdog' },
  { path: '/watchdog/void-register' },
]

/** The destinations search may offer: every page except the ones declared pre-auth. The CALLER still
 *  gates each one with `canAccessPath`, which is the one home for "may this viewer open this path" —
 *  this function only removes the pages nobody should ever be sent to from inside the app. */
export function searchableRoutes(): RouteEntry[] {
  return ROUTES.filter(r => !r.preauth)
}
