// GENERATED — do not edit the ROUTES array by hand.
//
// THE ONE HOME for "every page this app has". Derived by walking `src/app` with
// `node frontend/prove_route_index.mjs --bless`; the same file run WITHOUT `--bless` is the proof,
// and it FAILS THE BUILD when disk and this array disagree. That ratchet is the whole point: before
// it, 34 of 319 static pages were in no registry at all and therefore unfindable by any search in the
// product — including the one somebody actually asked for, `/account/password`. Curating the missing
// page would have left the other 33, so the registry is derived instead (the `module_graph.py`
// pattern, §50).
//
// THREE FIELDS ARE HUMAN and are PRESERVED across a re-bless:
//   label    — a derived label reads like a path ("Account → Password"); replace it with what people
//              call the page. A page that also has a nav entry takes the NAV label instead, because
//              that is the wording on the viewer's own screen.
//   aliases  — the words somebody would TYPE. For a page nav lists, aliases belong in
//              `ScreenLink.tsx` SCREENS instead: its guard requires every href to be a nav href,
//              which is mechanically why a page like `/account/password` can only declare them here.
//   preauth  — the REASON a page is deliberately not searchable (a sign-in screen, a public terms
//              page). Not a flag: the string is the reason, so an exclusion cannot be silent.
//
// Everything else about a page — may this viewer open it, what module gates it — stays where it
// already lives (`rbac.canAccessPath`, `canSeeItem`). This file says only WHAT EXISTS.
export type RouteEntry = {
  path: string
  label: string
  aliases?: string[]
  /** Why this page is deliberately not offered by search. Absent = searchable. */
  preauth?: string
}

export const ROUTES: RouteEntry[] = [
  { path: '/', label: 'Home', preauth: 'the marketing root — a signed-in user is redirected away from it' },
  { path: '/account/password', label: 'My Password', aliases: ['password reset', 'reset password', 'change password', 'change my password', 'forgot password', 'new password'] },
  { path: '/accounts', label: 'Accounts' },
  { path: '/accounts/analysis', label: 'Accounts → Analysis' },
  { path: '/accounts/balance-sheet', label: 'Accounts → Balance Sheet' },
  { path: '/accounts/cash-flow', label: 'Accounts → Cash Flow' },
  { path: '/accounts/companies', label: 'Accounts → Companies' },
  { path: '/accounts/cost-centers', label: 'Accounts → Cost Centers' },
  { path: '/accounts/device-payable', label: 'Accounts → Device Payable' },
  { path: '/accounts/device-purchases', label: 'Accounts → Device Purchases' },
  { path: '/accounts/inventory', label: 'Accounts → Inventory' },
  { path: '/accounts/journal', label: 'Accounts → Journal' },
  { path: '/accounts/liabilities-due', label: 'Accounts → Liabilities Due' },
  { path: '/accounts/pl', label: 'Accounts → Pl' },
  { path: '/accounts/profit-centers', label: 'Accounts → Profit Centers' },
  { path: '/accounts/recon', label: 'Accounts → Recon' },
  { path: '/accounts/residual-per-sub', label: 'Accounts → Residual Per Sub' },
  { path: '/accounts/royalty', label: 'Accounts → Royalty' },
  { path: '/accounts/royalty/recon', label: 'Accounts → Royalty → Recon' },
  { path: '/accounts/trends', label: 'Accounts → Trends' },
  { path: '/admin/access-log', label: 'Admin → Access Log' },
  { path: '/admin/billing', label: 'Admin → Billing' },
  { path: '/admin/billing-usage', label: 'Admin → Billing Usage' },
  { path: '/admin/business-types', label: 'Admin → Business Types' },
  { path: '/admin/carrier-documents', label: 'Admin → Carrier Documents' },
  { path: '/admin/control-box', label: 'Admin → Control Box' },
  { path: '/admin/dashboards', label: 'Admin → Dashboards' },
  { path: '/admin/fix-requests', label: 'Admin → Fix Requests' },
  { path: '/admin/impersonation', label: 'Admin → Impersonation' },
  { path: '/admin/import-health', label: 'Admin → Import Health' },
  { path: '/admin/kpi-metrics', label: 'Admin → Kpi Metrics' },
  { path: '/admin/labels', label: 'Admin → Labels' },
  { path: '/admin/menu', label: 'Admin → Menu' },
  { path: '/admin/org', label: 'Admin → Org' },
  { path: '/admin/org-chart', label: 'Admin → Org Chart' },
  { path: '/admin/pricing', label: 'Admin → Pricing' },
  { path: '/admin/roles', label: 'Admin → Roles' },
  { path: '/admin/security', label: 'Admin → Security' },
  { path: '/admin/support', label: 'Admin → Support' },
  { path: '/admin/support/docs', label: 'Admin → Support → Docs' },
  { path: '/admin/support/failures', label: 'Admin → Support → Failures' },
  { path: '/admin/support/fix-requests', label: 'Admin → Support → Fix Requests' },
  { path: '/admin/tenant-settings', label: 'Admin → Tenant Settings' },
  { path: '/admin/tenants', label: 'Admin → Tenants' },
  { path: '/admin/training', label: 'Admin → Training' },
  { path: '/admin/whats-new', label: 'Admin → Whats New' },
  { path: '/approvals', label: 'Approvals' },
  { path: '/chat', label: 'Chat' },
  { path: '/closing', label: 'Closing' },
  { path: '/closing/accessory-recon', label: 'Closing → Accessory Recon' },
  { path: '/closing/accountability', label: 'Closing → Accountability' },
  { path: '/closing/billpay-pickup', label: 'Closing → Billpay Pickup' },
  { path: '/closing/cash-config', label: 'Closing → Cash Config' },
  { path: '/closing/cash-position', label: 'Cash Position', aliases: ['cash on hand', 'cash position'] },
  { path: '/closing/cash-recon-management', label: 'Closing → Cash Recon Management' },
  { path: '/closing/count-config', label: 'Cash Count Setup', aliases: ['count config', 'denomination count'] },
  { path: '/closing/deposit-categories', label: 'Closing → Deposit Categories' },
  { path: '/closing/deposit-recon', label: 'Closing → Deposit Recon' },
  { path: '/closing/duplicates', label: 'Duplicate Closings', aliases: ['duplicate closing', 'double closing'] },
  { path: '/closing/envelope-config', label: 'Closing → Envelope Config' },
  { path: '/closing/envelope-payout', label: 'Closing → Envelope Payout' },
  { path: '/closing/envelope-report', label: 'Closing → Envelope Report' },
  { path: '/closing/epay-recon', label: 'Closing → Epay Recon' },
  { path: '/closing/expense-categories', label: 'Closing → Expense Categories' },
  { path: '/closing/expenses-report', label: 'Closing → Expenses Report' },
  { path: '/closing/external-credit-recon', label: 'Closing → External Credit Recon' },
  { path: '/closing/imports', label: 'Closing → Imports' },
  { path: '/closing/management', label: 'Closing → Management' },
  { path: '/closing/pickup', label: 'Closing → Pickup' },
  { path: '/closing/readiness', label: 'Closing Readiness', aliases: ['closing readiness', 'which stores closed'] },
  { path: '/closing/recon', label: 'Closing → Recon' },
  { path: '/closing/store-cash-on-hand', label: 'Closing → Store Cash On Hand' },
  { path: '/closing/store-visit-config', label: 'Store Visit Setup', aliases: ['store visit config', 'visit schedule setup'] },
  { path: '/closing/submit', label: 'Closing → Submit' },
  { path: '/closing/tender-config', label: 'Closing → Tender Config' },
  { path: '/closing/tender-recon', label: 'Closing → Tender Recon' },
  { path: '/closing/tender-recon-3way', label: 'Closing → Tender Recon 3way' },
  { path: '/closing/verify', label: 'Closing → Verify' },
  { path: '/commcalc', label: 'Commcalc' },
  { path: '/commcalc/accessory-cost-audit', label: 'Commcalc → Accessory Cost Audit' },
  { path: '/commcalc/accessory-definition', label: 'Commcalc → Accessory Definition' },
  { path: '/commcalc/accessory-flags', label: 'Commcalc → Accessory Flags' },
  { path: '/commcalc/activations', label: 'Commcalc → Activations' },
  { path: '/commcalc/agency', label: 'Commcalc → Agency' },
  { path: '/commcalc/asset', label: 'Commcalc → Asset' },
  { path: '/commcalc/asset/aging', label: 'Commcalc → Asset → Aging' },
  { path: '/commcalc/asset/aging-rebate', label: 'Commcalc → Asset → Aging Rebate' },
  { path: '/commcalc/asset/borrowed', label: 'Commcalc → Asset → Borrowed' },
  { path: '/commcalc/asset/charges/rma', label: 'Commcalc → Asset → Charges → Rma' },
  { path: '/commcalc/asset/dashboard', label: 'Commcalc → Asset → Dashboard' },
  { path: '/commcalc/asset/hotsheet-recon', label: 'Commcalc → Asset → Hotsheet Recon' },
  { path: '/commcalc/asset/inventory-recon', label: 'Commcalc → Asset → Inventory Recon' },
  { path: '/commcalc/asset/invoice-due', label: 'Invoices Due', aliases: ['invoice due', 'what do i owe'] },
  { path: '/commcalc/asset/lending', label: 'Commcalc → Asset → Lending' },
  { path: '/commcalc/asset/marketplace-purchases', label: 'Commcalc → Asset → Marketplace Purchases' },
  { path: '/commcalc/asset/missing-phones', label: 'Commcalc → Asset → Missing Phones' },
  { path: '/commcalc/asset/on-inventory', label: 'Commcalc → Asset → On Inventory' },
  { path: '/commcalc/asset/oninv-3way-recon', label: 'Three-Way Invoice Match', aliases: ['3 way match', 'invoice reconciliation', 'oninv recon'] },
  { path: '/commcalc/asset/owed-weekly', label: 'Commcalc → Asset → Owed Weekly' },
  { path: '/commcalc/asset/purchase-orders', label: 'Commcalc → Asset → Purchase Orders' },
  { path: '/commcalc/asset/purchase-orders/aging', label: 'Purchase Order Aging', aliases: ['po aging', 'old purchase orders'] },
  { path: '/commcalc/asset/purchase-orders/receiving', label: 'Receive a Purchase Order', aliases: ['receiving', 'receive stock', 'po receiving'] },
  { path: '/commcalc/asset/purchase-orders/tally', label: 'Purchase Order Tally', aliases: ['po tally'] },
  { path: '/commcalc/asset/purchase-orders/vendors', label: 'Purchase Order Vendors', aliases: ['po vendors', 'supplier list'] },
  { path: '/commcalc/atu-opportunity', label: 'Commcalc → Atu Opportunity' },
  { path: '/commcalc/bill-payments', label: 'Commcalc → Bill Payments' },
  { path: '/commcalc/carrier-comm-file', label: 'Commcalc → Carrier Comm File' },
  { path: '/commcalc/carrier-mapping', label: 'Commcalc → Carrier Mapping' },
  { path: '/commcalc/carrier-recon', label: 'Commcalc → Carrier Recon' },
  { path: '/commcalc/carrier-vs-pay', label: 'Commcalc → Carrier Vs Pay' },
  { path: '/commcalc/catalog', label: 'Commcalc → Catalog' },
  { path: '/commcalc/chargebacks', label: 'Commcalc → Chargebacks' },
  { path: '/commcalc/coaching', label: 'Commcalc → Coaching' },
  { path: '/commcalc/column-mapping', label: 'Commcalc → Column Mapping' },
  { path: '/commcalc/commission-category-map', label: 'Commcalc → Commission Category Map' },
  { path: '/commcalc/commission-discrepancy', label: 'Commcalc → Commission Discrepancy' },
  { path: '/commcalc/commission-explain', label: 'Why This Commission', aliases: ['explain commission', 'how was this paid', 'commission explain'] },
  { path: '/commcalc/commission-import', label: 'Commcalc → Commission Import' },
  { path: '/commcalc/commission-ledger', label: 'Commcalc → Commission Ledger' },
  { path: '/commcalc/commission-ledger/setup', label: 'Commission Ledger Setup', aliases: ['ledger setup', 'commission ledger mapping'] },
  { path: '/commcalc/commission-legs', label: 'Commcalc → Commission Legs' },
  { path: '/commcalc/commission-plans', label: 'Commcalc → Commission Plans' },
  { path: '/commcalc/commission-structure', label: 'Commcalc → Commission Structure' },
  { path: '/commcalc/comp-trend', label: 'Commcalc → Comp Trend' },
  { path: '/commcalc/connectors', label: 'Commcalc → Connectors' },
  { path: '/commcalc/custom-report', label: 'Commcalc → Custom Report' },
  { path: '/commcalc/daily-commission', label: 'Commcalc → Daily Commission' },
  { path: '/commcalc/device-cost-recon', label: 'Commcalc → Device Cost Recon' },
  { path: '/commcalc/device-history', label: 'Commcalc → Device History' },
  { path: '/commcalc/discrepancy', label: 'Commcalc → Discrepancy' },
  { path: '/commcalc/distributors', label: 'Commcalc → Distributors' },
  { path: '/commcalc/dlar-vs-platform', label: 'Commcalc → Dlar Vs Platform' },
  { path: '/commcalc/dlar/sweep', label: 'Commcalc → Dlar → Sweep' },
  { path: '/commcalc/email-imports', label: 'Commcalc → Email Imports' },
  { path: '/commcalc/epay-fee-recon', label: 'Commcalc → Epay Fee Recon' },
  { path: '/commcalc/epay/sweep', label: 'Commcalc → Epay → Sweep' },
  { path: '/commcalc/exec', label: 'Commcalc → Exec' },
  { path: '/commcalc/exec/mtd', label: 'Commcalc → Exec → Mtd' },
  { path: '/commcalc/expected-commission', label: 'Commcalc → Expected Commission' },
  { path: '/commcalc/expenses', label: 'Commcalc → Expenses' },
  { path: '/commcalc/financing', label: 'Commcalc → Financing' },
  { path: '/commcalc/financing/vendors', label: 'Financing Vendors', aliases: ['financing vendors', 'lease vendors'] },
  { path: '/commcalc/flags', label: 'Commcalc → Flags' },
  { path: '/commcalc/ftp-imports', label: 'Commcalc → Ftp Imports' },
  { path: '/commcalc/gp', label: 'Commcalc → Gp' },
  { path: '/commcalc/gp-category-map', label: 'Commcalc → Gp Category Map' },
  { path: '/commcalc/imei-rebates', label: 'Commcalc → Imei Rebates' },
  { path: '/commcalc/imei-recon', label: 'Commcalc → Imei Recon' },
  { path: '/commcalc/implementation', label: 'Commcalc → Implementation' },
  { path: '/commcalc/ingest-guard', label: 'Commcalc → Ingest Guard' },
  { path: '/commcalc/integrations', label: 'Commcalc → Integrations' },
  { path: '/commcalc/inventory-sold-recon', label: 'Commcalc → Inventory Sold Recon' },
  { path: '/commcalc/item-mapping', label: 'Commcalc → Item Mapping' },
  { path: '/commcalc/kpi', label: 'Commcalc → Kpi' },
  { path: '/commcalc/kpi-failing', label: 'Commcalc → Kpi Failing' },
  { path: '/commcalc/ma-class-wiring', label: 'Master Agent Class Wiring', aliases: ['ma class wiring', 'class wiring'] },
  { path: '/commcalc/ma-commission', label: 'Commcalc → Ma Commission' },
  { path: '/commcalc/ma-handsets', label: 'Commcalc → Ma Handsets' },
  { path: '/commcalc/ma-overview-recon', label: 'Commcalc → Ma Overview Recon' },
  { path: '/commcalc/ma-product-class', label: 'Commcalc → Ma Product Class' },
  { path: '/commcalc/ma-upload', label: 'Upload a Master Agent Statement', aliases: ['ma upload', 'upload statement', 'master agent upload'] },
  { path: '/commcalc/management-incentive', label: 'Commcalc → Management Incentive' },
  { path: '/commcalc/manager-followup', label: 'Commcalc → Manager Followup' },
  { path: '/commcalc/mapping', label: 'Commcalc → Mapping' },
  { path: '/commcalc/onboarding', label: 'Commcalc → Onboarding' },
  { path: '/commcalc/pay-simulator', label: 'Commcalc → Pay Simulator' },
  { path: '/commcalc/payables', label: 'Commcalc → Payables' },
  { path: '/commcalc/payout-plans', label: 'Commcalc → Payout Plans' },
  { path: '/commcalc/payout-schedules', label: 'Commcalc → Payout Schedules' },
  { path: '/commcalc/plan-assignment-audit', label: 'Plan Assignment Audit', aliases: ['plan assignment', 'who is on which plan'] },
  { path: '/commcalc/plan-installments', label: 'Commcalc → Plan Installments' },
  { path: '/commcalc/processor-ledger', label: 'Commcalc → Processor Ledger' },
  { path: '/commcalc/productivity', label: 'Commcalc → Productivity' },
  { path: '/commcalc/productivity-insights', label: 'Commcalc → Productivity Insights' },
  { path: '/commcalc/recovery', label: 'Commcalc → Recovery' },
  { path: '/commcalc/rep-aliases', label: 'Commcalc → Rep Aliases' },
  { path: '/commcalc/report-mappings', label: 'Report Column Mappings', aliases: ['report mappings', 'column mapping'] },
  { path: '/commcalc/reports', label: 'Commcalc → Reports' },
  { path: '/commcalc/reports-index', label: 'Commcalc → Reports Index' },
  { path: '/commcalc/sales-analyzer', label: 'Commcalc → Sales Analyzer' },
  { path: '/commcalc/sales-comparison', label: 'Commcalc → Sales Comparison' },
  { path: '/commcalc/sales-derive', label: 'Derive Sales From the Feed', aliases: ['sales derive', 'derive sales'] },
  { path: '/commcalc/sales-recon', label: 'Commcalc → Sales Recon' },
  { path: '/commcalc/sales-report', label: 'Commcalc → Sales Report' },
  { path: '/commcalc/schematic', label: 'Commcalc → Schematic' },
  { path: '/commcalc/settings', label: 'Commcalc → Settings' },
  { path: '/commcalc/store-match', label: 'Commcalc → Store Match' },
  { path: '/commcalc/target-fields', label: 'Commcalc → Target Fields' },
  { path: '/commcalc/targets', label: 'Commcalc → Targets' },
  { path: '/commcalc/targets/accessories', label: 'Commcalc → Targets → Accessories' },
  { path: '/commcalc/targets/action-plan', label: 'Commcalc → Targets → Action Plan' },
  { path: '/commcalc/targets/my', label: 'Commcalc → Targets → My' },
  { path: '/commcalc/targets/rep-map', label: 'Commcalc → Targets → Rep Map' },
  { path: '/commcalc/targets/settings', label: 'Commcalc → Targets → Settings' },
  { path: '/commcalc/tax-collected', label: 'Commcalc → Tax Collected' },
  { path: '/commcalc/upload', label: 'Commcalc → Upload' },
  { path: '/commcalc/upload/wizard', label: 'Commcalc → Upload → Wizard' },
  { path: '/commcalc/vendor-rebates', label: 'Commcalc → Vendor Rebates' },
  { path: '/commcalc/vip', label: 'Commcalc → Vip' },
  { path: '/commcalc/vip/paygo', label: 'Commcalc → Vip → Paygo' },
  { path: '/commcalc/vip/sweep', label: 'Commcalc → Vip → Sweep' },
  { path: '/commcalc/whatif', label: 'Commcalc → Whatif' },
  { path: '/commcalc/zero-sales', label: 'Commcalc → Zero Sales' },
  { path: '/compliance', label: 'Compliance' },
  { path: '/configurations', label: 'Configurations' },
  { path: '/crm', label: 'Crm' },
  { path: '/crm/agencies', label: 'Crm → Agencies' },
  { path: '/crm/leads', label: 'Crm → Leads' },
  { path: '/crm/leads/new', label: 'Crm → Leads → New' },
  { path: '/crm/lookup', label: 'Crm → Lookup' },
  { path: '/crm/my-followups', label: 'Crm → My Followups' },
  { path: '/crm/pipeline', label: 'Crm → Pipeline' },
  { path: '/crm/reports', label: 'Crm → Reports' },
  { path: '/crm/settings', label: 'Crm → Settings' },
  { path: '/employee', label: 'Employee' },
  { path: '/failures', label: 'Failures' },
  { path: '/franchise', label: 'Franchise' },
  { path: '/helpdesk', label: 'Helpdesk' },
  { path: '/helpdesk/dashboard', label: 'Helpdesk → Dashboard' },
  { path: '/helpdesk/new', label: 'Helpdesk → New' },
  { path: '/helpdesk/settings', label: 'Helpdesk → Settings' },
  { path: '/hr', label: 'Hr' },
  { path: '/hr/compliance', label: 'Hr → Compliance' },
  { path: '/hr/employee-database', label: 'Hr → Employee Database' },
  { path: '/hr/letters', label: 'Hr → Letters' },
  { path: '/hr/letters/queue', label: 'Letters Waiting to Send', aliases: ['letter queue', 'letters waiting'] },
  { path: '/hr/letters/send', label: 'Send a Letter', aliases: ['send letter', 'write a letter'] },
  { path: '/hr/letters/sent', label: 'Letters Already Sent', aliases: ['sent letters', 'letter history'] },
  { path: '/hr/onboarding', label: 'Hr → Onboarding' },
  { path: '/hr/payroll-expenses', label: 'Hr → Payroll Expenses' },
  { path: '/hr/people', label: 'Hr → People' },
  { path: '/login', label: 'Login', preauth: 'the sign-in screen — nobody searches for it from inside the app' },
  { path: '/marketing', label: 'Marketing' },
  { path: '/marketing/events/new', label: 'Marketing → Events → New' },
  { path: '/marketing/my-checkins', label: 'Marketing → My Checkins' },
  { path: '/marketing/sales-from-events', label: 'Marketing → Sales From Events' },
  { path: '/marketing/settings', label: 'Marketing → Settings' },
  { path: '/notify', label: 'Notify' },
  { path: '/notify/report-recipients', label: 'Notify → Report Recipients' },
  { path: '/onboarding/intake', label: 'Onboarding → Intake' },
  { path: '/operator', label: 'Operator' },
  { path: '/operator/audit', label: 'Operator → Audit' },
  { path: '/operator/billing', label: 'Operator → Billing' },
  { path: '/operator/notices', label: 'Operator → Notices' },
  { path: '/operator/operators', label: 'Operator → Operators' },
  { path: '/operator/tenants', label: 'Operator → Tenants' },
  { path: '/payroll', label: 'Payroll' },
  { path: '/portal', label: 'Employee Portal', aliases: ['portal', 'my portal'] },
  { path: '/pos/activation-report', label: 'Pos → Activation Report' },
  { path: '/pos/activations', label: 'Pos → Activations' },
  { path: '/pos/customers', label: 'Pos → Customers' },
  { path: '/pos/import', label: 'Pos → Import' },
  { path: '/pos/inventory', label: 'Pos → Inventory' },
  { path: '/pos/onboarding', label: 'Pos → Onboarding' },
  { path: '/pos/products', label: 'Pos → Products' },
  { path: '/pos/receipts', label: 'Pos → Receipts' },
  { path: '/pos/reports', label: 'Pos → Reports' },
  { path: '/pos/sales', label: 'Pos → Sales' },
  { path: '/pos/settings', label: 'Pos → Settings' },
  { path: '/pos/special-orders', label: 'Pos → Special Orders' },
  { path: '/pos/special-orders/manage', label: 'Pos → Special Orders → Manage' },
  { path: '/pos/vendors', label: 'Pos → Vendors' },
  { path: '/privacy', label: 'Privacy', preauth: 'a public policy page, not a place to do work' },
  { path: '/referral', label: 'Referral' },
  { path: '/referral/approvals', label: 'Referral → Approvals' },
  { path: '/referral/list', label: 'Referral → List' },
  { path: '/referral/new', label: 'Referral → New' },
  { path: '/referral/settings', label: 'Referral → Settings' },
  { path: '/remediation', label: 'Remediation' },
  { path: '/reports', label: 'Reports' },
  { path: '/signup', label: 'Signup', preauth: 'the sign-up screen — reached before there is an account' },
  { path: '/storeops', label: 'Storeops' },
  { path: '/storeops/accountability', label: 'Storeops → Accountability' },
  { path: '/storeops/admin', label: 'Storeops → Admin' },
  { path: '/storeops/attendance', label: 'Storeops → Attendance' },
  { path: '/storeops/closing', label: 'Store Closing', aliases: ['store closing', 'close the store'] },
  { path: '/storeops/dm-accessory-attribution', label: 'Accessory Attribution by Manager', aliases: ['dm accessory', 'accessory attribution'] },
  { path: '/storeops/employees', label: 'Storeops → Employees' },
  { path: '/storeops/hours-budget', label: 'Storeops → Hours Budget' },
  { path: '/storeops/payroll', label: 'Storeops → Payroll' },
  { path: '/storeops/payroll-change-log', label: 'Payroll Change Log', aliases: ['payroll changes', 'who changed pay'] },
  { path: '/storeops/payroll-tax', label: 'Storeops → Payroll Tax' },
  { path: '/storeops/payroll/approvals', label: 'Storeops → Payroll → Approvals' },
  { path: '/storeops/payroll/payers', label: 'Storeops → Payroll → Payers' },
  { path: '/storeops/reports', label: 'Storeops → Reports' },
  { path: '/storeops/reviews', label: 'Storeops → Reviews' },
  { path: '/storeops/reviews/config', label: 'Storeops → Reviews → Config' },
  { path: '/storeops/salary-advances', label: 'Salary Advances', aliases: ['salary advance', 'pay advance', 'loan to employee'] },
  { path: '/storeops/schedule', label: 'Storeops → Schedule' },
  { path: '/storeops/setup/employees', label: 'Storeops → Setup → Employees' },
  { path: '/storeops/setup/insurance', label: 'Storeops → Setup → Insurance' },
  { path: '/storeops/setup/stores', label: 'Storeops → Setup → Stores' },
  { path: '/storeops/shift-extensions', label: 'Storeops → Shift Extensions' },
  { path: '/storeops/staffing', label: 'Storeops → Staffing' },
  { path: '/storeops/swaps', label: 'Storeops → Swaps' },
  { path: '/storeops/team', label: 'Storeops → Team' },
  { path: '/storeops/timeclock', label: 'Storeops → Timeclock' },
  { path: '/storeops/timeclock-permissions', label: 'Storeops → Timeclock Permissions' },
  { path: '/storeops/timeoff', label: 'Storeops → Timeoff' },
  { path: '/storeops/visits', label: 'Storeops → Visits' },
  { path: '/storeops/visits/new', label: 'Log a Store Visit', aliases: ['new visit', 'log a visit', 'store visit'] },
  { path: '/storeops/visits/plan', label: 'Storeops → Visits → Plan' },
  { path: '/storeops/visits/settings', label: 'Storeops → Visits → Settings' },
  { path: '/supply/cart', label: 'Supply → Cart' },
  { path: '/supply/compare', label: 'Supply → Compare' },
  { path: '/supply/orders', label: 'Supply → Orders' },
  { path: '/supply/vendors', label: 'Supply → Vendors' },
  { path: '/terms', label: 'Terms', preauth: 'a public policy page, not a place to do work' },
  { path: '/training', label: 'Training' },
  { path: '/vision', label: 'Vision' },
  { path: '/vision/activity', label: 'Vision → Activity' },
  { path: '/vision/behavior', label: 'Vision → Behavior' },
  { path: '/vision/busy-hours', label: 'Vision → Busy Hours' },
  { path: '/vision/heatmap', label: 'Vision → Heatmap' },
  { path: '/vision/lines', label: 'Vision → Lines' },
  { path: '/vision/onboarding', label: 'Vision → Onboarding' },
  { path: '/vision/settings', label: 'Vision → Settings' },
  { path: '/watchdog', label: 'Watchdog' },
  { path: '/watchdog/void-register', label: 'Watchdog → Void Register' },
]

/** The destinations search may offer: every page except the ones declared pre-auth. The CALLER still
 *  gates each one with `canAccessPath`, which is the one home for "may this viewer open this path" —
 *  this function only removes the pages nobody should ever be sent to from inside the app. */
export function searchableRoutes(): RouteEntry[] {
  return ROUTES.filter(r => !r.preauth)
}
